### ISSUE TITLE
Add Sparse PK Methods

### ISSUE THREAD

**Issue by billdenney** [billdenney/pknca#1]
A suggestion from ACoP 2015 was to add sparse PK methods.

References include: 
Bailer: http://www.ncbi.nlm.nih.gov/pubmed/3221328
Nedelman: http://www.ncbi.nlm.nih.gov/pubmed/7724473
Holder's extension to Nedelman: https://www.ncbi.nlm.nih.gov/pubmed/11459444 (https://doi.org/10.1081/BIP-100104199)
Navarro-Fontestad: http://dx.doi.org/10.1002/pst.484
Yuan: http://www.ncbi.nlm.nih.gov/pubmed/8360854

**Comment by wolfsem** [comment]
Dear Colleagues,

You may find of interest that sparse PK methods are available in the R package PK  

References include: 
- Jaki T., Wolfsegger M. J. and Ploner M. (2009). Confidence intervals for ratios of AUCs in the case of serial sampling: A comparison of seven methods. Pharmaceutical Statistics, 8(1):12-24.
- Jaki T. and Wolfsegger M. J. (2009). A theoretical framework for estimation of AUCs in complete and incomplete sampling designs. Statistics in Biopharmaceutical Research, 1(2):176-184.
- Wolfsegger M. J. and Jaki T. (2009). Non-compartmental Estimation of Pharmacokinetic Parameters in Serial Sampling Designs. Journal of Pharmacokinetics and Pharmacodynamics, 36(5):479-494.
- Jaki T., Wolfsegger M. J. and Lawo J-P. (2010). Establishing bioequivalence in complete and incomplete data designs using AUCs. Journal of Biopharmaceutical Statistics, 20(4):803-820.
- Jaki T. and Wolfsegger M. J. (2012). Non-compartmental estimation of pharmacokinetic parameters for flexible sampling designs. Statistics in Medicine, 31(11-12):1059-1073.

Best regards

Martin

**Comment by billdenney** [comment]
Sparse NCA is now implemented as an initial support built-in.  Right now, the only parameter that can be calculated is "sparse_auclast".  That will also generate the "sparse_auclast_se" and "sparse_auclast_df".  Limitations remain, but PKNCA has taken the big step of working with sparse data!

To use it, you can use the `sparse` argument to `PKNCAconc()`.  A vignette is coming soon.
