### ISSUE TITLE
Individual plots of fitted half-life

### ISSUE THREAD

**Issue by kirstenbergmann** [billdenney/pknca#100]
Hi Bill

I'm just getting started with using the PKNCA package and have some questions, which I will share in different "issues".

I would like to plot the individual observed concentrations vs time with the observations included in the derivation of the half-life marked (colored) and overlaid with the fitted line. To generate this plot myself, I need to know the intercept of the linear regression. Is there a way to extract this information? (I just realized that you are working on plots like this in the pknca.reporting package, but would still like to make the plots myself until this package becomes available). 

Regards
Kirsten

**Comment by billdenney** [comment]
Hi Kirsten,

I’m glad that you’re starting out with PKNCA, and I appreciate that you separated the separate questions into separate issues making them easier to respond to and easier for others to find.

When I generate these figures, I use three parts of the NCA output: lambda.z, clast.pred, and tlast which fully define the line.

Thanks,

Bill

**Comment by kirstenbergmann** [comment]
Thank you Bill! This seems obvious once you know it :)
