### ISSUE TITLE
Validation of PKNCA

### ISSUE THREAD

**Issue by kirstenbergmann** [billdenney/pknca#101]
As a new user of PKNCA, one of my first question regards the validation of the package. Two questions related to this: 
- What exactly is validated when running the validation script that is provided with the PKNCA package?
- Has the functions in PKNCA been compared (validated) against similar functions in winnonlin?

**Comment by billdenney** [comment]
The validation script runs all of the tests that are run to confirm the accuracy of package results.  These tests confirm that both the scientific results are accurate (such as, half-life and various AUCs are accurate) and that programmatic results are accurate (such as, confirming that functions are receiving reasonable inputs and if not reasonable, that errors are given).

Multiple groups have confirmed consistent results between PKNCA and their internal tools (including WinNonlin), but when these comparisons have been shared with me to date they have been shared confidentially (with an allowance to say that they exist).  So, I can answer that people have tested it with no differences to essentially machine precision, but I cannot provide those documents.  (There is an effort underway to publish something, but it is not yet available.)
