### ISSUE TITLE
Rounding of derived parameters

### ISSUE THREAD

**Issue by kirstenbergmann** [billdenney/pknca#103]
Hi Bill

It would be convenient if it was possible to implement business rules for rounding of PK parameters for inclusion of the parameters in the PP SDTM domain or presentation in a listing (also relevant in case CDISC is not used). In general, I would like to report Cmax (and dose-normalized Cmax), tmax, tlag etc (actual observed parameters) with the same number of significant figures as in the input concentration time data. For derived PK parameters (AUC, CL, V, half-life, lambda etc) the PhUSE PK white paper from 2014 suggest rounding to 3 significant figures, but I guess that each company could would have their own preference. 

Is this something that is already implemented in the PKNCA package or does this request belong here?

Best regards
Kirsten

**Comment by billdenney** [comment]
@kirstenbergmann, here is the moved issue.
