### ISSUE TITLE
AUC using other methods e.g. linear trapezoidal rule

### ISSUE THREAD

**Issue by AlrisAldon2017** [billdenney/pknca#105]
How can I calculate AUC using linear trap, and linear-log, and linear-up, log-down? Are all these methods implemented in the PKNCA software?
Thanks
Alfred

**Comment by billdenney** [comment]
Hi Alfred,

Linear trapezoidal (`'linear'`) and linear-up/log down (`'lin up/log down'`) are both supported.  Linear-log is not yet supported (see #23).

To set the calculation method globally for the current R session, you can use:
```r
PKNCA.options(auc.method="linear")
PKNCA.options(auc.method="lin up/log down")
```

To set it for a specific calculation run, you can use
```r
PKNCAdata(..., options=list(auc.method="linear"))
PKNCAdata(..., options=list(auc.method="lin up/log down"))
```

**Comment by AlrisAldon2017** [comment]
Thanks so much
Alfred
