### ISSUE TITLE
tests not installed

### ISSUE THREAD

**Issue by kirstenbergmann** [billdenney/pknca#108]
Hi Bill 

We are installing PKNCA using the following command:
install.packages(pkgs="PKNCA", INSTALL_opts="--install-tests")

However, the tests as not downloaded with the installation (no PKNCA/tests folder). Is this an issue with the currently version of the PKNCA package? 

Best regards
Kirsten

**Comment by billdenney** [comment]
I'm guessing that you're either installing from Windows or Mac.  I believe that you need to install from source to get the tests:

`install.packages(pkgs="PKNCA", INSTALL_opts="--install-tests", type = "source")`

Can you please try that and see if it works?

**Comment by kirstenbergmann** [comment]
That did the trick :) Thanks.
