### ISSUE TITLE
aucall provides same outcome as auclast 

### ISSUE THREAD

**Issue by kirstenbergmann** [billdenney/pknca#109]
Hi Bill

I'm trying to get a good understaning of the different AUC functions in PKNCA. I'm using PKNCA version 0.9.1. I expect that aucall should provide a different result than auclast in case of BLQ data. This is also the case in the AUC Calculation vignette, but I cannot reproduce these results. See below.  Outcome is:
  start end subject PPTESTCD  PPORRES exclude
1     0  24       1  auclast 12.99658    <NA>
2     0  24       1   aucall 12.99658    <NA>

```r
my_conc <- data.frame(conc=c(0, 2.5, 3, 2, 1.5, 1.2, 1.1, 0, 0),
                      time=c(0:5, 8, 12, 24),
                      subject=1)
my_conc$BLOQ <- my_conc$conc == 0
my_conc$measured <- TRUE

conc_obj <- PKNCAconc(my_conc, conc~time|subject)
data_obj <- PKNCAdata(data.conc=conc_obj,
                      intervals=data.frame(start=0,
                                           end=24,
                                           aucall=TRUE,
                                           auclast=TRUE))
results_obj <- pk.nca(data_obj)
as.data.frame(results_obj)
```

**Comment by billdenney** [comment]
When I run the code you provide, I get different answers for auclast and aucall, as expected:

``` r
library(PKNCA)

my_conc <- data.frame(conc=c(0, 2.5, 3, 2, 1.5, 1.2, 1.1, 0, 0),
                      time=c(0:5, 8, 12, 24),
                      subject=1)
my_conc$BLOQ <- my_conc$conc == 0
my_conc$measured <- TRUE

conc_obj <- PKNCAconc(my_conc, conc~time|subject)
data_obj <- PKNCAdata(data.conc=conc_obj,
                      intervals=data.frame(start=0,
                                           end=24,
                                           aucall=TRUE,
                                           auclast=TRUE))
results_obj <- pk.nca(data_obj)
#> No dose information provided, calculations requiring dose will return NA.
as.data.frame(results_obj)
#>   start end subject PPTESTCD  PPORRES exclude
#> 1     0  24       1  auclast 12.99658    <NA>
#> 2     0  24       1   aucall 15.19658    <NA>
```

<sup>Created on 2019-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kirstenbergmann** [comment]
Hi Bill

Thanks for the quick reply! I now found out that the difference is caused by the conc.blq option. I had used the following:
conc.blq=list(first="keep",middle="drop",last="drop")

I thought that last="drop" was needed to not include BLQ values of 0 in calculation of half-life (not calculated here, but in another calculation), but that seems not to be the case.  

regards
Kirsten

**Comment by billdenney** [comment]
Great!  I’m glad that you figured it out.
