### ISSUE TITLE
Validation of PKNCA 0.9.1

### ISSUE THREAD

**Issue by kirstenbergmann** [billdenney/pknca#111]
Hi Bill

Now I managed to install the PKNCA 0.9.1 package with the tests scripts and re-did the validation. However, the result column looks weird on my screen. Is this something to do with my windows settings, or is it something on you side? 

Best regards
Kirsten

[PKNCA-validation V0.9.1_2019-09017.pdf](https://github.com/billdenney/pknca/files/3625666/PKNCA-validation.V0.9.1_2019-09017.pdf)

**Comment by billdenney** [comment]
Hi Kirsten,

I noticed the same issue yesterday.  Something changed in the way that testthat makes data.frames of results.  I updated the vignette yesterday on GitHub, but until that is released on CRAN, the summary where it says all tests passed should cover you.  (Or, you could download the updated vignette from https://raw.githubusercontent.com/billdenney/pknca/master/vignettes/PKNCA-validation.Rmd and run it.)

**Comment by kirstenbergmann** [comment]
Excellent. I used the code you provided and it works well. Thanks!
