### ISSUE TITLE
Use of more than one exclude function

### ISSUE THREAD

**Issue by kirstenbergmann** [billdenney/pknca#113]
Hi Bill 

Would it be possible to program the exclude function such that more than one exclude can be used, e.g.

my.results <- exclude(my.results,FUN=exclude_nca_min.hl.r.squared())
my.results <- exclude(my.results,FUN=exclude_nca_span.ratio())
my.results <- exclude(my.results,FUN=exclude_nca_max.aucinf.pext())

such that a text will be added to the exclude column when this is NA in the input my.results file.

best regards
Kirsten

**Comment by billdenney** [comment]
Sorry for the very long radio silence on this issue.  I just created a reproducible example for this and I just applied a commit a fix it.
