### ISSUE TITLE
compute half life with only two data points

### ISSUE THREAD

**Issue by slyrus** [billdenney/pknca#114]
It would be nice if one could compute a half-life from only two points.

---

This works:
```r
PKNCA::pk.calc.half.life(conc=c(1, 0.5, 0.25),
                         time=c(0, 1, 2),
                         min.hl.points=3,
                         allow.tmax.in.half.life=TRUE,
                         check=FALSE)
```
but this doesn't:
```r
PKNCA::pk.calc.half.life(conc=c(1, 0.5),
                         time=c(0, 1),
                         min.hl.points=2,
                         allow.tmax.in.half.life=TRUE,
                         check=FALSE)
```

**Comment by billdenney** [comment]
Thank you for pointing this out.  I just fixed it.

The underlying issue had to do with the fact that adjusted r-squared requires 3 points for calculation.  Now adjusted r-squared with 2 points or fewer is `NA` instead of an error.
