### ISSUE TITLE
RELREC

### ISSUE THREAD

**Issue by VincentBuchheit** [billdenney/pknca#120]
Hi, 

Is it possible to create RELREC from PKNCA?

**Comment by billdenney** [comment]
Hi Vincent,

PKNCA doesn't directly support RELREC, but a simplified RELREC is possible to generate from its output.

What I mean by "simplified RELREC" is that it is very straight-forward to use the interval definitions to determine which group of points were used to calculate a parameter, and at the next level of complexity, it is also relatively straight-forward to give a direct link from the input data to Cmax and Tmax (by the interval, the Tmax value, and the start of the interval) and half-life (by the interval, start time, and Tlast).  Most other parameters use all the data within the interval.

Does that answer your question?

**Comment by VincentBuchheit** [comment]
Hi Bill,

it does, thanks!

Kind regards


Vincent Buchheit


Clinical Pharmacology Data Scientist Head

Senior Manager

Pharmaceutical Sciences

Roche Pharma Research and Early Development



Roche Innovation Center Basel



F. Hoffmann-La Roche Ltd
Grenzacherstrasse 124
4070 Basel

Switzerland

Phone +41 61 68 83 767

Mobile +41 79 87 78 267

The right dose for every patient
<https://www.youtube.com/watch?v=Xrnb_CZbW8c>

The benefits of using modeling and simulation in drug development
<http://www.youtube.com/watch?v=o2ntCRCgpUM&list=PL4C70CE64C0E14B30&index=7>

The benefits of using Pharmacokinetic and Pharmacodynamic modeling
<http://www.youtube.com/watch?v=jxvJHXVIV4E&list=PL4C70CE64C0E14B30&index=6>

The benefits of using Clinical Trial Simulation
<http://www.youtube.com/watch?v=dW4fek6plP4&list=PL4C70CE64C0E14B30&index=5>

Disease modeling to inform clinical trial simulation
<http://www.youtube.com/watch?v=Hhd2U94QM60&list=UUH_ZBgtt6-8-VA52pao0SSA>

Entry Into Humans video <https://www.youtube.com/watch?v=LNCEqjN0swU>
