### ISSUE TITLE
Individual subject NCA estimates and 95% upper limit 

### ISSUE THREAD

**Issue by Ravua1992** [billdenney/pknca#121]
Hello, 

I am using the code shown below for my NCA.  Just wanted to know how do I get the Individual estimates and 95% upper limit for the NCA parameters specifically AUC and Cmax ? 

Thank you,
Abhigyan 
```
# Load the package
library(PKNCA)
# Set the business rule options with the PKNCA.options() function
# Load your concentration-time data
myrawconcdata <- read.csv("myconc.csv", stringsAsFactors=FALSE)
# Load your dose data
myrawdosedata <- read.csv("mydose.csv", stringsAsFactors=FALSE)
# Put your concentration data into a PKNCAconc object
myconc <- PKNCAconc(data=myrawconcdata,
                    formula=conc~time|treatment+subject/analyte)
# Put your dose data into a PKNCAdose object
mydose <- PKNCAdose(data=myrawdosedata,
                    formula=dose~time|treatment+subject)
# Combine the two (and automatically determine the intervals of
# interest
mydata <- PKNCAdata(myconc, mydose)
# Compute the NCA parameters
myresults <- pk.nca(mydata)
# Summarize the results
summary(myresults)

```

**Comment by billdenney** [comment]
Hi Abhigyan,

You can get the individual estimates by running `as.data.frame(myresults)`.  You could use a function that you write with `PKNCA.set.summary()` to compute the confidence interval, but it is probably simpler to just compute it manually from the individual statistics.

**Comment by Ravua1992** [comment]
Thank you Bill.  
I saved the results as data.frame and computed the interval manually.
