### ISSUE TITLE
CPT Tutorial/Poster for pknca

### ISSUE THREAD

**Issue by Ravua1992** [billdenney/pknca#124]
Hello Bill, 

Is there any CPT tutorial for PKNCA ? (similar to ggplot2) (https://www.ncbi.nlm.nih.gov/pubmed/24132163)

I have found that github and youtube video are good starting point for beginners to get going with PKNCA. Is there some other source which I might have missed or not aware about ?  

Thanks,
Abhi

**Comment by billdenney** [comment]
That would be a good idea, but there's not one yet.  I'll keep that in mind.  The other item I'd point you to are the vignettes.  They are easiest to access on CRAN: https://cran.r-project.org/web/packages/PKNCA/index.html

As you're learning, tutorials or documentation suggestions are always welcome!
