### ISSUE TITLE
PKNCA Issue 

### ISSUE THREAD

**Issue by aalhadab** [billdenney/pknca#125]
I am getting the following error message
Requesting an AUC range starting (0) before the first measurement (1) is not allowed

I did not change my NCA settings or data and it used to work 

> mposim <- posim %>% group_by(M,DOSE,TIME) %>% summarise(mean=mean(DV)) 

> mposim 
# A tibble: 153 x 4
# Groups:   M, DOSE [10]
       M  DOSE  TIME   mean
   <dbl> <dbl> <dbl>  <dbl>
 1     0     5   0   0     
 2     0     5   1   0.0462
 3     0     5   1.5 0.0925
 4     0     5   2   0.147 
 5     0     5   2.5 0.204 
 6     0     5   3   0.258 
 7     0     5   4   0.343 
 8     0     5   6   0.396 
 9     0     5   8   0.356 
10     0     5  12   0.278 
# ... with 143 more rows

> mposim %>% filter(M==1)
# A tibble: 71 x 4
# Groups:   M, DOSE [5]
       M  DOSE  TIME  mean
   <dbl> <dbl> <dbl> <dbl>
 1     1     5   0   0.904
 2     1     5   1   1.95 
 3     1     5   1.5 2.11 
 4     1     5   2   2.32 
 5     1     5   2.5 2.52 
 6     1     5   3   2.73 
 7     1     5   4   3.03 
 8     1     5   6   3.13 
 9     1     5   8   2.90 
10     1     5  12   2.43 
# ... with 61 more rows

> conc <- PKNCAconc(mposim %>% filter(TIME!=0), mean~TIME|M+DOSE) 

> dose <- PKNCAdose(data = mposim %>% filter(TIME==0 & mean==0) ,DOSE~TIME|M+DOSE, route = "extravascular" )

> my.intervals <- data.frame(M=c(0, 1),
                            start=c(0, 0),
                            end=c(Inf, 24),
                            cmax=c(T,T),
                            aucinf.obs=c(T, F),
                            auclast=c(F, T))

> ncapo_r<-PKNCAdata(conc, dose, intervals = my.intervals)

> poresult <- pk.nca(ncapo_r)$result %>% 
   filter(PPTESTCD %in%c("cmax","aucinf.obs","auclast")) %>% 
   spread(PPTESTCD,PPORRES) 
There were 11 warnings (use warnings() to see them)

> poresult
   start end M DOSE exclude aucinf.obs auclast        cmax
1      0  24 1    5    <NA>         NA      NA   3.1326539
2      0  24 1   25    <NA>         NA      NA  15.6715970
3      0  24 1   50    <NA>         NA      NA  31.2158609
4      0  24 1  100    <NA>         NA      NA  62.7910270
5      0  24 1  200    <NA>         NA      NA 123.9385375
6      0 Inf 0    5    <NA>         NA      NA   0.3958811
7      0 Inf 0   25    <NA>         NA      NA   4.8876109
8      0 Inf 0   50    <NA>         NA      NA  12.1662920
9      0 Inf 0  100    <NA>         NA      NA  27.4731046
10     0 Inf 0  150    <NA>         NA      NA  39.1303660

**Comment by billdenney** [comment]
That error indicates that at least one individual does not have a time zero measurement in the dataset.  Please check that every individual has a time 0 measurement.

**Comment by Sibojang9** [comment]
Missing time zero measurement is very commonly seen in PK datasets. It would be tremendously handy if PKNCA can provide an argument to fill these missing values. For example：
`PKNCAconc(PKdata, Result~Time|ID, fill_time_zero=TRUE)`

**Comment by billdenney** [comment]
Hi Sibo,

I understand that data corrections like this would help in many cases, but rather than this type of one-off correction (for single-dose, extravascular dosing), I'd want the fix to cover all cases. of the combinations of:

* extravascular, intravascular bolus, or intravascular infusion
* predose  for first dose or predose at steady-state

Creating the the `fill_time_zero` option would add a feature that would need to be managed with the future scenario though without covering the full needs for the overarching feature.

**Comment by Sibojang9** [comment]
I completely agree; I look forward to seeing future regimens of these scenarios.

**Comment by Sibojang9** [comment]
Hi Bill, any update on this feature? I am not sure if this feature has been implemented in the latest version. Thanks.

**Comment by billdenney** [comment]
Hi @Sibojang9, there is no progress on this yet.  I closed this as a duplicate of #21, so to keep issues organized, I'd prefer to have the discussion there.
