### ISSUE TITLE
Efficient way to link mrgsolve output to pknca 

### ISSUE THREAD

**Issue by Ravua1992** [billdenney/pknca#126]
Hello, 
I am trying to simulate from model and link output form mrgsolve to pknca for 2 cohorts(multiple dose). After saving the output as data framed called SIM, I am doing the following and performing NCA, stratified by ID, Cohort

```
 myrawconcdata<-SIM%>%filter(evid!=1)
 myrawdosedata <- SIM%>% select(evid,ID,time,COH,amt)%>%filter(evid==1)

myconc_MAD <- PKNCAconc(data=myrawconcdata,
                    formula=conc~time|COH+ID)

mydose_MAD <- PKNCAdose(data=myrawdosedata,
                    formula=amt~time|COH+ID,route="extravascular")


mydata_mad <- PKNCAdata(myconc_MAD, mydose_MAD,intervals=intervals_manual,options=list(auc.method="lin up/log down"))
myresults_mad <- pk.nca(mydata_mad)
```

**Comment by billdenney** [comment]
That looks like it should work.  Is this to help others or am I missing a question?

**Comment by Ravua1992** [comment]
Hi Bill, it was not a question exactly. Its more about how can i make the connection from mrgsovle to Pnkca more direct without the intermediate steps which are listed above. is there some function which can recognize mrgsolve format output and perform the nca as an additional step after simulation without the manual steps ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by billdenney** [comment]
There has been some discussion of this in the past, but there is not currently a way to simplify out those manual steps.  The previous discussions are at:

* metrumresearchgroup/mrgsolve#303
* #62

It is a reasonable idea, but it's not something that is currently a top priority.  If you were able to write a pull request that covered most of the reasonable use cases, I'd be happy to include it.

**Comment by Ravua1992** [comment]
Thanks for clarification Bill. 
Closing this issue for now.

**Comment by Ravua1992** [comment]
Hello Bill, 
I am trying to understand how to implement pknca in various situations. 
In this case, I request calculation on PK parameters using summarize function.

`NCA<-SIM%>%group_by(ID) %>%
  summarise(CMAX=pk.calc.cmax(conc,time),TMAX=pk.calc.tmax(conc,time),
            AUC=pk.calc.auc(conc,time))`

is this a reasonable approach to link output from mrgsolve?
other question is when should one use this approach vs approach shown above (where in we define dose and concentration objects first and calculate the nca parameters) ?
