### ISSUE TITLE
When to use pk.calc.* functions or pk.nca()

### ISSUE THREAD

**Issue by billdenney** [billdenney/pknca#127]
Hello Bill, 
I am trying to understand how to implement pknca in various situations. 
In this case, I request calculation on PK parameters using summarize function.

`NCA<-SIM%>%group_by(ID) %>%
  summarise(CMAX=pk.calc.cmax(conc,time),TMAX=pk.calc.tmax(conc,time),
            AUC=pk.calc.auc(conc,time))`

is this a reasonable approach to link output from mrgsolve?
other question is when should one use this approach vs approach shown above (where in we define dose and concentration objects first and calculate the nca parameters) ?

_Originally posted by @Ravua1992 in https://github.com/billdenney/pknca/issues/126#issuecomment-602131930_

**Comment by billdenney** [comment]
@Ravua1992, to help others find new questions or issues, can you please open new issues to separate them?

For the single-dose case, using the `pk.calc.*()` functions directly is reasonable.  I very rarely do it because other aspects controlled by the normal interface going through `pk.nca()` like subsetting for intervals are often useful to me.  The only time that I recommend this is when doing simulations with *many* individuals needing calculations, and you know that you've subset it to the right times for the calculations that you want.  ... and, you know that your data have no issues (like time that may not be sorted or no duplicated time points for an individual).

Overall what I'm trying to say is:  It's not a problem if you know that your data are good, but for me, it's usually worth it to use `pk.nca()` because of the additional supports that it provides.

**Comment by Ravua1992** [comment]
Sounds good bill. Thanks. 
I will post questions as new issues next time.
