### ISSUE TITLE
exclude_nca

### ISSUE THREAD

**Issue by toothpicky** [billdenney/pknca#129]
I am trying to exclude parameters based on the parameter values but I am not sure how to use these functions as described in the manual:

exclude_nca_span.ratio(min.span.ratio)
exclude_nca_max.aucinf.pext(max.aucinf.pext)
exclude_nca_min.hl.r.squared(min.hl.r.squared)

When I type them in, all I get in return is the source code.

**Comment by billdenney** [comment]
They are used as the `FUN` argument to the `exclude()` function.

The example from the documentation for `exclude_nca` shows how to use them:

```r
my_conc <- PKNCAconc(data.frame(conc=1.1^(3:0),
                                time=0:3,
                                subject=1),
                     conc~time|subject)
my_data <- PKNCAdata(my_conc,
                     intervals=data.frame(start=0, end=Inf,
                                          aucinf.obs=TRUE,
                                          aucpext.obs=TRUE))
my_result <- pk.nca(my_data)
my_result_excluded <- exclude(my_result,
                              FUN=exclude_nca_max.aucinf.pext())
as.data.frame(my_result_excluded)
```
