### ISSUE TITLE
Cast summary(PKNCAresults)

### ISSUE THREAD

**Issue by tcacek** [billdenney/pknca#13]
It would be nice to have a "cast.PKNCAresult" to create exportable file with NCA results in column form (not list form).

**Comment by billdenney** [comment]
When casting, how would you differentiate parameters that were never requested for calculation from those where calculation was not possible?  Both could be NA or we could add columns to indicate if the calculation was "Done" or "Not Done".

Those two options don't feel quite right for me (though I lean toward the NA option with a warning printed if there are unrequested NA values in the data).

**Comment by tcacek** [comment]
Would it be possible to add * and ** directly to the column space where the values were either not calculated or not able to be calculated? With * meaning not calculated and ** meaning not able to be calculated.  Maybe use a statement such as “if isnull, *..” I’m just brain storming now.

 

Once I become more versed in PKNCA, it will be better able to make suggestions

**Comment by billdenney** [comment]
Changing to asterisks will change the data from numeric to character.  It just occurred to me that we have NaN (not a number) and NA to work with as missing.  I'll try those.

**Comment by billdenney** [comment]
You can get the output in a wide format with `as.data.frame(results, out.format="wide")`.
