### ISSUE TITLE
Reactive PKNCADose Object

### ISSUE THREAD

**Issue by Ravua1992** [billdenney/pknca#130]
I am trying to pass subset of a reactive data to create PKNCAdose object and I am getting the following error. 
```
Error in PKNCAdose.data.frame: The left side formula must be a variable in the data, empty, or '.'.
``` 
Does this mean that the formulae.dose is unable to recognize Dose ~ Time|Subject ?  
```
    f1 = as.formula(paste(input$ncacon,"~",Time<-toString(input$ncatime),"|",Subject<-toString(input$ncasubid)))
    f2 = as.formula(paste(input$ncadose,"~",Time<-toString(input$ncatime),"|",Subject<-toString(input$ncasubid)))
    NCAdata <- PKNCAdata(data.conc=myrawconcdata, formula.conc =(f1), data.dose = myrawdosedata,formula.dose =(f2))
```
I am not sure why is this the case when I am using the exact same approach to create my PKNCAconc object ?

Thank you,

**Comment by billdenney** [comment]
Without more context, I can only guess about the actual cause.  The error indicates that the variable `input$ncadose` is not in `myrawdosedata`.

There is no reason that PKNCA should have a specific error with a reactive variable, but the reactive object will, in essence, have to be a data.frame or something equivalent when going into `PKNCAdata()` or `PKNCAdose()`.

I would try troubleshooting by printing `names(myrawdosedata)` and `input$ncadose` to the console.

**Comment by Ravua1992** [comment]
Thanks for suggestions bill. I tried printing the data and it was a data issue. This is resolved.
