### ISSUE TITLE
question about auc0-t and auc0-inf calculation 

### ISSUE THREAD

**Issue by Ravua1992** [billdenney/pknca#131]
Hi Bill, 
If I have a nonmem dataset which has DV= NA @ t=0. 
What is the best way to implement in pknca ? I manually changed DV=0 @ t=0 and compute pk parameters. 
However, In my output I am unable to compute AUC0-t and AUC0-inf after setting manual intervals (0-24 annd inf).
Any suggestion how to fix this or why in the output I am unable to compute AUC although other paramters such as Cmax, tmax, lambda.z etc.. are working as expected. 

Thank you,

**Comment by billdenney** [comment]
PKNCA usually gives an informative warning message in this case.  Can you please share a reproducible example?
