### ISSUE TITLE
clearance calculation at steady state

### ISSUE THREAD

**Issue by JoannaPeng** [billdenney/pknca#132]
Is there an option to calculate clearance using dose & auctau at steady state?

I have the following codes:

```
my.conc <- PKNCAconc(conc, DV~Time|VISIT+SUBJID/Analyte)
my.dose <- PKNCAdose(dose, DOSE~Time|VISIT+SUBJID, route="extravascular", duration=0)
my.intervals=data.frame(start=0,end=Inf,auclast=T, aucinf.obs=T,aucpext.obs=TRUE,cl.obs=TRUE)
```

The serial PK data are from an oncology study and VISIT=C1D1 and C2D1. At C2D1 steady state should be reached. And I would like to calculate the clearance using C2D1 auctau (tau=24 hrs for daily dosing), but not C1D1 aucinf because the half-life is ~20 hrs, so aucinf based on samples over 24 hrs was not accurate. I can add R code to calculate the clearance outside of PKNCA, but wonder whether this can be done easily within PKNCA.

**Comment by billdenney** [comment]
Yes, you can do this with PKNCA.  The simplest way would be something like the code below.  The important details are:

* You can define different calculations using different grouping variables added to your intervals data.frame (note that I added `VISIT` here for that purpose).
* Each row of an intervals data.frame can have different calculations performed, so you don't have to do the same calculations in each interval.
* I assume that time starts at 0 for each visit.  If not, you will need to update the `start` and `end` times in `my.intervals`.

```
my.conc <- PKNCAconc(conc, DV~Time|VISIT+SUBJID/Analyte)
my.dose <- PKNCAdose(dose, DOSE~Time|VISIT+SUBJID, route="extravascular", duration=0)
my.intervals <-
  data.frame(
    VISIT=c("C1D1", "C2D1"),
    start=0,
    end=c(Inf, 24),
    auclast=TRUE,
    aucinf.obs=c(TRUE, FALSE),
    aucpext.obs=c(TRUE, FALSE),
    cl.last=c(FALSE, TRUE)
  )
```

**Comment by JoannaPeng** [comment]
Thanks, Bill! I didn't see cl.last in the PKNCA package documentation. But your code is extremely helpful!!!

**Comment by billdenney** [comment]
I have hopes of a documentation clean-up that will make the list of parameters easier to find and use.  I'm glad that it worked for you!

**Comment by JoannaPeng** [comment]
Hi Bill,

A follow-up question using IV infusion data.  Doses are 2 weeks (336 hrs) apart, and after the 5th dose (DOSE.NUM=5), steady state is reached. 

`my.conc <- PKNCAconc(conc, DV~Time|DOSE.NUM+SUBJID) 
my.dose <- PKNCAdose(dose, DOSE~Time|DOSE.NUM+SUBJID, route="intravascular", duration="EXDUR")   

my.intervals <-
  data.frame(
    DOSE.NUM=c(1, 5),
    start=0,
    end=c(Inf, 336), 
   ...
    half.life=TRUE, 
   ....
    auclast=TRUE,
    aucinf.obs=c(TRUE, FALSE),
       
    cl.obs=c(TRUE, FALSE),
    cl.last=c(FALSE, TRUE),   
    
    vss.iv.obs=c(TRUE, FALSE),
    vss.iv.last=c(FALSE, TRUE),
    
    mrt.iv.obs=c(TRUE, FALSE),
    mrt.iv.last=c(FALSE, TRUE),
    
    thalf.eff.iv.obs=c(TRUE, FALSE),
    thalf.eff.iv.last=c(FALSE, TRUE)
)`

How are vss.iv.last and mrt.iv.last after the 5th dose (at steady state) calculated using PK.NCA? Is mrt.iv.last calculated as AUMClast/AUClast? vss.iv.last should be calculated as MRTINF*CL where CL is cl.last. Is MRTINF calculated by default and used to derive vss.iv.last, even though only mrt.iv.last is specified in the code above?

Thank you!
