### ISSUE TITLE
calculate partial AUC using actual sampling times 

### ISSUE THREAD

**Issue by JoannaPeng** [billdenney/pknca#133]
How to calculate partial AUC for a given interval (e.g., 0-24 hrs) using actual sampling times in PKNCA? The example is related to my previous question for which the serial PK data are from an oncology study with daily dosing and VISIT=C1D1 and C2D1.

Protocol times were used for the 1st round of analysis, but now the actual times will be used for the 2nd round of analysis. So there will be cases where the 24 hrs samples were actually collected before or after 24hrs post-dose, or even missing.

**Comment by billdenney** [comment]
You can use something like the following for your analysis.  You will likely want to manually impute the time 0 concentration (usually by shifting the predose concentration to time 0).

After that, you can set your intervals to something like:

```r
my_interval <-
  data.frame(
    start=0, end=24,
    aucint.last=TRUE
  )
```

The `aucint.*` AUCs calculate with interpolation and extrapolation.

**Comment by JoannaPeng** [comment]
When I used the codes below, I got an error message. But the data were sorted already. 
```
my_interval <-
  data.frame(
    CYCLE=c(1,3),  # 
    start=0, end=21,
    aucint.last=TRUE  
  )

my_data <- PKNCAdata(my.conc, my.dose, intervals=my_interval)
my_results <- pk.nca(my_data)
```

Error in `purrr::pmap()`:
In index: 10.
Caused by error in `assert_time()`:
! Please report a bug.
Error with interval start=0, end=21: Assertion on 'time' failed: Must be sorted.

Interestingly, when I ran the following codes, there was no error:
```
my.intervals <-
  data.frame(
    CYCLE=c(1,3),
    start=0,
    end=c(Inf,28),  # use 28 days, not 21 days, because some subjects had their last sample taken later than 21 days
    auclast=TRUE
)

mydata <- PKNCAdata(my.conc, my.dose, intervals=my.intervals)
myresults <- pk.nca(mydata)

```
How to fix the error?

**Comment by billdenney** [comment]
Can you please open this as a new issue since it is not directly related to this issue?

And, can you please share a full reproducible example with blinded data? Any "Please report a bug" error relates to something that shouldn't happen and usually needs example data to find the underlying issue.

**Comment by JoannaPeng** [comment]
I figured out the issue. The data were sorted by the nominal time, but should have been sorted by the actual time.

**Comment by JoannaPeng** [comment]
A different but related question. Is there an option to calculate CL using aucint.last (a partial AUC) at steady state? I know there is an option to calculate CL (cl.last) using auclast at steady state, but auclast is not optimal if tlast is very different from tau for whatever reason. It seems that I have to calculate CL using aucint.last (which is auctau) outside of PKNCA, correct?

**Comment by billdenney** [comment]
All of the `aucint` parameters are variations on `auctau`. I think that you're right that there isn't a clearance related to `aucint.last`. There is a different issue that is tracking parameters that need to be added. Can you please add it to the list there?
