### ISSUE TITLE
IV infusion with different durations 

### ISSUE THREAD

**Issue by JoannaPeng** [billdenney/pknca#135]
How to conduct NCA for IV infusions with different durations for different subjects? Here is my code.

my.conc <- PKNCAconc(conc, DV~TIME|SUBJID)

my.dose <- PKNCAdose(dose, DOSE~TIME|SUBJID, route="intravascular", duration="EXDUR_C1D1"/60) 

where EXDUR_C1D1 is a column in 'dose' and shows the infusion duration (in minutes) for each subject. "EXDUR_C1D1"/60 has the unit in hrs.

With this code, I got an error message saying that Error in "EXDUR_C1D1"/60 : non-numeric argument to binary operator.

**Comment by billdenney** [comment]
The issue here is not PKNCA, but just that R interprets "EXDUR_C1D1"/60 as trying to divide text by a number.  You would need to perform that division in a new column of your data and provide that column to PKNCA like:

```r
dose$dur_minutes <- dose$EXDUR_C1D1/60
my.dose <- PKNCAdose(dose, DOSE~TIME|SUBJID, route="intravascular", duration="dur_minutes")
```

**Comment by JoannaPeng** [comment]
Thank you, Bill!
Joanna
