### ISSUE TITLE
superposition from steady state and from 2 doses

### ISSUE THREAD

**Issue by mahmed452** [billdenney/pknca#137]
i have PK data at steady. drug was administered as 20 mg qid till reaching the steady state. PK data was collected only at steady state for 2 doses (20 mg q6 h). As i don't have the PK data from the first dose, i would like to use superposition to predict the data at first dose. also, the second dose peak seems to be lower than the first dose. this may be due to food effect. how do i used the second dose to predict exposure for the third and 4th dose of the day with food while using the first dose to predict the first dose of the day exposure (fasting).
is there a way to simulate a dosing regimen of 20  mg qid on the first day (none steady state) using superposition form these 2 doses at steady state. the first dose need to show fasting state, the second, third and fourth dose needs to show fed state.

**Comment by billdenney** [comment]
Overall, this is a modeling problem and not an NCA problem.  Superposition is convolution of data, and your question above is deconvolution.

I would recommend population PK modeling as the preferred solution to this problem rather than deconvolution of superposition data.
