### ISSUE TITLE
Specific different dosing regimen for different subjects

### ISSUE THREAD

**Issue by mahmed452** [billdenney/pknca#138]
i am trying to use superposition to predict data at steady state. my data has 4 groups and each group need to receive different dosing regimen to match the exposure. how do i do this within PKNCA.

**Comment by billdenney** [comment]
I don't understand the question as there are two interpretations.

1. Do you have 1 group of source data with a single dosing regimen and you want to generate superposition for 4 different dosing regimens from that?
2. Do you have 4 groups of source data each with different dosing regimens and you want to generate superposition for each of the 4 groups with the same dosing regimen as in the source data?
3. (or something else)

Can you please give the specific dosing regimens for the source data and the desired superposition for the generated data?  (Like, "Source is 20 mg single dose and I want to generate 100 mg QD steady-state data," or, "Source is 5 mg single dose, and I want to generate 50 mg dosed with breakfast, lunch, and dinner PK after 5 days of dosing.")

**Comment by mahmed452** [comment]
thanks for quick reply
the source data is single dose 20 mg for different renal function groups (normal, mild, moderate, severe renal impairment groups). since we want to match the exposure for all groups, we would like to administer different dosing regimen (with different interval as well that is titrated over a month--so it is complex dosing with different dosing interval within each group according to the following:
1) normal group: 10 mg QD for a week then 10 mg BID for a week, then 30 mg (10 mg morning+20 mg evening) over a week, then 20 mg BID over a week
2) mild group: 10 mg QD for 3 week then 20 mg BID over a week
3) moderate group: 10 mg q48 h for 2 week and then 10 mg QD for 2 week, then 10 mg BID 
4) severe group: 10 mg q72h for 2 weeks and then 10 mg q48 h for 2 weeks, then 10 mg QD

**Comment by billdenney** [comment]
You will need to subset your data to each of the groups and run them separately (i.e. run once for normal then once for mild then once for moderate then for severe).  Here is the example of how to run it for the normal group, and you can modify the dose amount and times for the others:

```r
library(PKNCA)
library(dplyr, quietly=TRUE)

## Load the PK concentration data
theoph_corrected <- datasets::Theoph
theoph_corrected$conc[theoph_corrected$Time == 0] <- 0
d_conc <-
  as.data.frame(theoph_corrected) %>%
  mutate(Subject=as.numeric(as.character(Subject)))
## Generate the dosing data
d_dose <- d_conc[d_conc$Time == 0,]
d_dose$Time <- 0

## Create a concentration object specifying the concentration, time, and
## subject columns.  (Note that any number of grouping levels is
## supported; you are not restricted to just grouping by subject.)
conc_obj <-
  PKNCAconc(
    d_conc,
    conc~Time|Subject
  )
## Create a dosing object specifying the dose, time, and subject
## columns.  (Note that the grouping factors should be the same as or a
## subset of the grouping factors for concentration, and the grouping
## columns must have the same names between concentration and dose
## objects.)
dose_obj <-
  PKNCAdose(
    d_dose,
    Dose~Time|Subject
  )

# Set the "dose.times" and "dose.amount" arguments to the actual dose times you
# want to use for the group
superposition(
  conc_obj,
  dose.input=10,
  dose.times=
    c(
      (0:6)*24, # QD times for a week
      seq(7, 13.5, by=0.5)*24 # BID times for a week
    ),
  dose.amount=
    c(
      rep(10, 7), # QD doses
      rep(c(10, 20), 7) # BID doses
    ),
  tau=168*2, # tau must be longer than the maximum time for a dose
  n.tau=1 # n.tau is 1 because you are specifying every dose (which is required for the titration)
)
```
