### ISSUE TITLE
Plot points used in Lz determination

### ISSUE THREAD

**Issue by tcacek** [billdenney/pknca#14]
Would be nice to have a (plot.Lz.points) function to visualize those points (and associated regression line) associated with determining Lz slope.

**Comment by billdenney** [comment]
I'm planning plotting more in a future version (probably 2-3 versions from now).  My general plans for plotting are:

- Plot concentration/time data (currently done with plot.PKNCAconc)
- Plot concentration+dosing/time data (arrows where doses are administered)
- Improved versions of both of the above separating out times when NCA parameters are requested vs. not requested (making plot breaks expanding the axis when parameters are requested and condensing the axis at times between).
    - The intent is to condense trough-only PK between dense PK in a subject's profile.
- Within all of the above:
    - Represent BLQ differently than above the LOQ
    - Represent lz points and the half-life curve

If you have other parts that you'd like to see plotted, please add them to this thread!

**Comment by ksl31** [comment]
Hi Bill, 
Is the function "plot.PKNCAconc" currently in the package?

**Comment by billdenney** [comment]
plot.PKNCAconc should be available in all versions of PKNCA.  You should be able to simply call the plot function on your concentration data.  As an example:

    myconc <- PKNCAconc(...)
    plot(myconc)

**Comment by billdenney** [comment]
All aspects of reporting will be moving to the PKNCA.reporting package.  This issue is migrating there.
