### ISSUE TITLE
Question: How to include/exclude points with pk.calc.half.life()

### ISSUE THREAD

**Issue by billdenney** [billdenney/pknca#143]
Could you also include an example on doing the same start/end time selection using the 
`pk.calc.half.life`  function?  

When I pass my dataset (modified as you have above with the excluded time points) into the function as follows
`data  %>% 
mutate(hl=list(pk.calc.half.life(conc=conc,Time,
manually.selected.points = TRUE, options=list(exclude_half.life="hl_exclude"), 
check=FALSE)))`

 It isn't recognizing my excluded values.  What is the proper way to implement this more interactively?

_Originally posted by @fisherjm in https://github.com/billdenney/pknca/issues/136#issuecomment-802109689_

**Comment by billdenney** [comment]
@fisherjm, when you call the `pk.calc.xxx()` functions directly, they do not know of anything in the data.frame.  `exclude_half.life` only applies when using `pk.nca()` to do the calculations.

Separately, `exclude_half.life` is an argument for the `PKNCAconc()` function and not an option.  The valid options are defined here: https://cran.r-project.org/web/packages/PKNCA/vignettes/Options-for-Controlling-PKNCA.html

What you want to do is perform the exclusion on `conc` and `time` as you pass them into `pk.calc.half.life()` and then use `manually.selected.points = TRUE` to indicate that automatic point selection should not occur.

**Comment by billdenney** [comment]
I have updated the documentation to clarify what are valid options and with a bit more clarity on `manually.selected.points`.

**Comment by fisherjm** [comment]
Thanks, Bill.  I think I understand better now. Yes, clarifying that in the documentation would help, I think.  It wasn't clear if the exclude column could be passed as an argument in pk.calc.half.life.  Thanks!

**Comment by billdenney** [comment]
I'm glad that it is now clearer.  If you have any specific suggestions for the documentation, help there is always appreciated!  As the author, it is sometimes too easy to see it from my point of view from when I wrote the code and docs rather than the parts that could be confusing to others.
