### ISSUE TITLE
Calculating multi-dose mrt and Vss

### ISSUE THREAD

**Issue by paconius** [billdenney/pknca#144]
Hello, 
PKNCA is a great package. Thanks to the authors for maintaining this for the community.

I am trying to analyze a set of data collected on the last day (0-24h) of a multi-day dosing experiment. As a result, I need to calculate the special steady-state PK parameters: cl.last, mrt.md.obs, vss.md.obs, instead of the typical parameters used when analyzing single-dose data (see issue #44 for more details on these special parameters).

When I try to run the following analysis, I get an error telling me that I didn't specify tau.
```
conc_obj <- PKNCAconc(data, conc~time|id)
d_dose <- data[data$time == min(data$time),]
dose_obj <- PKNCAdose(data = d_dose, formula = dose~time|id, route="intravascular", time.nominal="time")
intervals_manual <- data.frame(start=0, end=24, auclast=TRUE, cl.last=TRUE, mrt.md.obs=TRUE, vss.md.obs=TRUE)
data_obj_manual <- PKNCAdata(conc_obj, dose_obj,intervals=intervals_manual)
```

>  Error in (function (conc, time, volume, duration.conc, dose, time.dose,  : 
>  Error with interval id=1, start=0, end=24: Cannot find argument 'tau' for NCA function 'pk.calc.mrt.md' 

It makes perfect sense that it is complaining about the missing tau value since the tau value is needed to calculate the multi-dose mrt. Searching through the online examples and docs, the only way I can see to specify tau is to use the superposition() function. However, this function appears to take single-dose data and extrapolates what the multi-dose concentrations would look like. Since I am already starting with the multi-day concentration data, superposition() doesn't seem to be what is needed in my case.

Is there another way I can specify that tau = 24h?

Thank you!

**Comment by paconius** [comment]
I've been doing more research and found that I was missing a key piece of info. To perform the mrt.md.obs calc, you not only need tau, but also a single-dose AUC0->inf estimate -- which obviously wouldn't be available with my dataset. Asa a result, I withdraw my question. Since I can't delete it, I will simply close the item.

**Comment by billdenney** [comment]
You're right that this is a more complex parameter to calculate.  It is a less-common study design to have all the information needed for calculation (the design would be a single dose with a full washout followed by multi-dose).

I find that most people use one of the mrt calculations that assume linearity-- even for multiple dosing and even when PK are not linear.
