### ISSUE TITLE
mrt cannot be calculated

### ISSUE THREAD

**Issue by ksl31** [billdenney/pknca#15]
mrt cannot be calculated when manual interval is specified as follows, 

my.intervals <- data.frame(start=0,
                           end=inf,
                           cmax=TRUE,
                           tmax=TRUE,
                           auclast=TRUE,
                           aucinf=TRUE,
                           aumclast=TRUE,
                           aumcinf=TRUE,
                           aucall=TRUE,
                           aumcall=TRUE,
                           mrt=TRUE)

Error message:
 
Error in pk.nca.interval(conc = tmpconcdata[, col.conc], time = tmpconcdata[,  : 
  Cannot find argument 'auc' for NCA function 'pk.calc.mrt'

**Comment by ksl31** [comment]
Just to follow up. Parameters related to MRT also cannot be calculated. These include Kel (=1/MRT), Vss (=CL x MRT), and Vz (=Dose/(AUC x Kel)).

**Comment by billdenney** [comment]
I'm about to commit a fix for mrt.  mrt is the same as MRTinf, and I just added mrt.last which is MRTlast.  Can you please confirm that this fix works for you?

**Comment by biju-benjamin** [comment]
Firstly thanks very much for your wonderful work., 

setting mrt.inf=TRUE does not seem to solve the problem. the following is output 
Error in pk.nca.interval(conc = tmpconcdata[, col.conc], time = tmpconcdata[,  : 
  Cannot find argument 'aucinf' for NCA function 'pk.calc.mrt'

**Comment by billdenney** [comment]
@biju-benjamin Can you please try setting "mrt.obs" (which is MRT calculated from the AUCinf,obs) or "mrt.pred" (which is MRT calculated from AUCinf,pred)?

**Comment by biju-benjamin** [comment]
setting mrt.obs does not seem to work. the following is the output

Error in pk.nca.interval(conc = tmpconcdata[, col.conc], time = tmpconcdata[,  : 
  Cannot find argument 'aucinf' for NCA function 'pk.calc.mrt'

For the automatic setting however, aucinf is computed.
This is my second trial with the package. Hoping to find some time working around.  will keep you updated. Thanks

**Comment by billdenney** [comment]
Can you try reinstalling from either GitHub or CRAN and see if it works for you?  I just did the following, and it worked without error for me:

```
library(PKNCA)
my.conc <- PKNCAconc(as.data.frame(datasets::Theoph), conc~Time|Subject)
d.dose <- unique(datasets::Theoph[datasets::Theoph$Time == 0,
                                  c("Dose", "Time", "Subject")])
my.dose <- PKNCAdose(d.dose, Dose~Time|Subject)
my.data.automatic <- PKNCAdata(my.conc, my.dose,
                               intervals=data.frame(start=0, end=Inf, mrt.obs=TRUE))
my.results.automatic <- pk.nca(my.data.automatic)
my.results.automatic$result
```

If you're still having the error, can you please provide a reproducible example with the error?
