### ISSUE TITLE
conflict with tbl_df class from dplyr

### ISSUE THREAD

**Issue by trangmichael** [billdenney/pknca#16]
After calling `PKNCAdose` and `PKNCAconc` to d.dose and d.conc data frames which are also of the tbl_df class because I created them through dplyr, I run into an error when calling PKNCAdata:

```
Error in `$<-.data.frame`(`*tmp*`, "start", value = list(tsld = 0)) : 
  replacement has 1 row, data has 2
```

It works if I coerce d.dose and d.conc to a data frame (removing the tbl_df class) using the code below:

```
nca.conc <- PKNCAconc(data.frame(d.conc),
                     conc~tsld|group+id)

nca.dose <- PKNCAdose(data.frame(d.dose),
                     ~tsld|group+id)
```

We can provide a reproducible example if necessary.

**Comment by billdenney** [comment]
A reproducible example would help.  To help generate a reproducible example, the dput command can help make objects easier to export.

**Comment by trangmichael** [comment]
Here's code to generate a data frame of PK data:

```r
library(PKNCA)
library(dplyr)

set.seed(2891)

d.conc <- expand.grid(subject = seq(4), 
            dose = 100, 
            cl = 5,
            v = 10,
            time = seq(from = 0, to = 24, by = 1)
            ) %>% 
  mutate(noise = rnorm(n = nrow(.), mean = 0, sd = 0.2),
         conc = dose/v * exp(-cl/v * time) + noise) %>% 
  arrange(subject, time) %>% 
  tbl_df

d.dose <- d.conc %>% 
  filter(time == 0) %>% 
  unique %>% 
  tbl_df

lapply(list(d.conc, d.dose), class)
```

```
## [[1]]
## [1] "tbl_df"     "tbl"        "data.frame"
## 
## [[2]]
## [1] "tbl_df"     "tbl"        "data.frame"
```

```r
my.conc <- PKNCAconc(d.conc, conc~time|subject)
my.dose <- PKNCAdose(d.dose, dose~time|subject)

my.data.automatic <- PKNCAdata(my.conc, my.dose)
```

```
## Error in `$<-.data.frame`(`*tmp*`, "start", value = structure(list(time = 0), .Names = "time", row.names = c(NA, : replacement has 1 row, data has 2
```

```r
sessionInfo()

## R version 3.1.2 (2014-10-31)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## 
## locale:
## [1] LC_COLLATE=English_United States.1252 
## [2] LC_CTYPE=English_United States.1252   
## [3] LC_MONETARY=English_United States.1252
## [4] LC_NUMERIC=C                          
## [5] LC_TIME=English_United States.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] dplyr_0.4.3 PKNCA_0.7  
## 
## loaded via a namespace (and not attached):
##  [1] assertthat_0.1  DBI_0.3.1       digest_0.6.9    doBy_4.5-13    
##  [5] evaluate_0.8.3  formatR_1.2     grid_3.1.2      htmltools_0.2.6
##  [9] knitr_1.12.3    lattice_0.20-33 lazyeval_0.1.10 magrittr_1.5   
## [13] markdown_0.7.4  MASS_7.3-40     Matrix_1.2-4    nlme_3.1-118   
## [17] parallel_3.1.2  plyr_1.8.3      R6_2.1.2        Rcpp_0.12.4    
## [21] rmarkdown_0.9.5 splines_3.1.2   stringi_1.0-1   stringr_1.0.0  
## [25] survival_2.37-7 tools_3.1.2
```

**Comment by billdenney** [comment]
I'm about to commit a change that simply makes the as.data.frame part of your code implicit. The way that column subsetting happens between data.frame and tbl_df classes would cause changes throughout the package.

Please let me know if this fixes your issue.

I'm going to leave this issue open for now as an enhancement to go through the code and make it work with tbl_df more directly.

P.S. Your example code had negative concentrations, so I exponentiated the noise in your test:

    ## ...
    mutate(noise = rnorm(n = nrow(.), mean = 0, sd = 0.2),
           conc = dose/v * exp(-cl/v * time) * exp(noise)) %>% 
    ## ...

**Comment by sibojan** [comment]
I got the same issue with this because my raw dataset was input through readr::read_csv other than th e conventional read.csv.  read_csv generates the tbl_df by default.

**Comment by billdenney** [comment]
@sibojan Can you try with the current version on GitHub?  If you're still having an issue, can you please provide a reproducible example (the GitHub version currently works for the example given by @trangmichael.

**Comment by sibojan** [comment]
It does work for me now with the Github version.  I used to download that from CRAN through Rstudio. I think that most R beginner still use this way to install new package.

**Comment by sibojan** [comment]
Hi Bill, I listened to your youtube webinar this week. After that, I
started the NCA by following the instruction on your slides, on which the
installation method is library(PKNCA). You may want to update your slides
with the Github way.

**Comment by billdenney** [comment]
I'd rather have people install from CRAN unless they specifically know that they want the development version from GitHub.  Many people want more traceability of their results than installing from GitHub allows.

The GitHub version will always be the same or more current than the CRAN version.
