### ISSUE TITLE
Steady-state PK parameters

### ISSUE THREAD

**Issue by Sibojang9** [billdenney/pknca#163]
Hi Bill,

Given a dataset with multiple-dose PK profile, is PKNCA capable to calculate the time to reach steady-state and the related Ctrough-ss, Cpeak-ss, and AUCtau-ss. I searched around but cannot find the sample code/dataset from the PKNCA vignettes. If so, could you please kindly share an example to implement that function.  

Thanks,
Sibo 
Pfizer

**Comment by billdenney** [comment]
Hi Sibo,

I think that the answer is yes for all of these, but it doesn't have a vignette yet (good idea to add one).

Time to steady-state is calculable with the `pk.tss()` function (http://billdenney.github.io/pknca/reference/pk.tss.html).  I would recommend using the monoexponential method.

I'm not certain that I'm going to answer the Ctrough-ss, Cpeak-ss, and AUCtau-ss question the way you intend.  So, if you're expecting other parameters, please let me know.  To calculate these three, I would add `ctrough`, `cmax`, and one of the variants of AUCint (probably one of `aucint.all`, `aucint.inf.obs`, or `aucint.inf.pred`) to your intervals for the steady-state dense PK time interval.

**Comment by Sibojang9** [comment]
Hi Bill,

Thanks for the hints. Once `ctrough`, `cmax`, and one of the variants of AUCint can get the steady-state PK, we don't need to add additional functions. Is there any example to implement the `pk.tss` function to actual data?  it will be very helpful if we can have a vignette to demo the steady-state PK coding using PKNCA.  Thank you for supporting that idea.

**Comment by billdenney** [comment]
@Sibojang9, I've added a vignette for time to steady-state.  Please take a look and let me know if you think it is readable or if there are clarifications that could help: http://billdenney.github.io/pknca/articles/v22-time-to-steady-state.html
