### ISSUE TITLE
wide format output

### ISSUE THREAD

**Issue by sibojan** [billdenney/pknca#17]
You may add an augment to pk.nca function to let users choose long or wide format output. The default is the long format but wide format might be more intuitive for visual inspection and subsequent manipulation. Right now, I am using the tidyr::spread to reshape the result manually, like  final.result[[1]] %>% spread(PPTESTCD,PPORRES)

**Comment by billdenney** [comment]
Thanks for the suggestion (and the code that does what you're looking for).

I think that this is similar to issue #13 .  I'll keep them as separate because they request different functions, but they will likely be implemented at the same time.

**Comment by sibojan** [comment]
That is great. Thank you.

**Comment by billdenney** [comment]
You can get the output in a wide format with `as.data.frame(results, out.format="wide")`.
