### ISSUE TITLE
Selection of points for terminal phase calculation

### ISSUE THREAD

**Issue by ksl31** [billdenney/pknca#18]
it would be nice to be able to select terminal phase points individually.

**Comment by billdenney** [comment]
There are a few ways that I've seen point selection done before.  I think that you're wanting the first way, but let me confirm:

1. Fully individual point selection:  Point-by-point, choose if you want it (or not) in the half-life.  You may or may not choose any point including Tlast.
2. First and last point selection:  Choose the first and last point.  Every point between those two would be included.
3. First point selection:  Choose the first point, and the last point defaults to Tlast.

Also, when you exclude a point from a half-life calculation do you want to keep it for other calculations (like AUC)?  If you want to drop it from AUC and other calculations, I'd recommend dropping it from the dataset before the run.  (I don't think this is what you're looking for, but I wanted to be sure the option was considered.)

**Comment by ksl31** [comment]
Thank you for your reply. Yes, I think the first way is the most flexible and useful. Yes I want to keep the point for my AUC and other calculations. Basically just trying to get same output with Winnolin. Thanks!

**Comment by dennisanoe** [comment]
Bill,

I would like to second the request for adding a capability to specify the time points to be included in the calculation of lambdaz. I would be happy with the simplest option above: Choose the first point, and the last point defaults to Tlast. (If Tlast or any  other time point is to be excluded from the calculation of lambdaz it should be excluded from the calculation of all other parameters - which is handled by excluding it from the working dataset). The lambdaz estimates that are calculated wqould would be evaluated for reportability by criteria established for minimum data point number, R2 (or adjR2), and most importantly span ratio.

I have found the Dunne algorithm for selection of terminal phase data points to be unsatisfactory in ascending dose studies where, at lower doses with BQL results at later time points, apparent log-linear data runs in early disposition phases will mistakenly be assigned to the terminal phase. I believe that a reliable and consistent terminal phase start time can only be reliably assigned by the data analyst after examining all the PK profiles from the study in aggregate. 

Thanks.

**Comment by billdenney** [comment]
Hi,

I plan to have this in the next release.

As a temporary work-around if you only need the half-life and lambdaz (and not AUCinf with the same half-life), you can make an interval with only the points of interest in it.

Thanks,

Bill

**Comment by dennisanoe** [comment]
Thanks for your quick response. I am delighted that this feature will be present in future versions.

**Comment by billdenney** [comment]
FYI, this is implemented in a fix that's about to be committed.  I need to add some more documentation, but you can now use the `include_half.life` and `exclude_half.life` arguments to the PKNCAconc function.  If you have any issues with the fix, please open a new issue (since an issue with the implementation will no longer be a feature request).
