### ISSUE TITLE
Two questions on interval definitions

### ISSUE THREAD

**Issue by RaySub** [billdenney/pknca#189]
---
Hello,

When specifying manual intervals, auclast will not show unless it is manually enabled.

```r
library(PKNCA)
source(url("https:///raw.githubusercontent.com//billdenney//pknca//main//tests//testthat//generate.data.R"))

#' Generate dose information to go with concentration data.
#'
#' @param concdata Concentration-time data generated by
#' \code{\link{generate.conc}}
#' @return A data frame of dosing data
generate.dose <- function(concdata) {
  ret <-
    unique(
      concdata[
        ,
        setdiff(names(concdata), c("time", "conc", "analyte"))
      ]
    )
  ret$dose <- as.numeric(factor(ret$treatment))
  ret$time <- 0
  ret
}


d_conc <-
  PKNCAconc(
    generate.conc(nsub=1,
                  ntreat=1,
                  time.points=c(0, 1, 2, 4, 6, 8, 12, 24, 36, 48),
                  nstudies=1,
                  nanalytes=1,
                  resid=0),
    conc~time|treatment+ID)
print(d_conc)

intervals_manual <-
  data.frame(
    start=0,
    end=c(24, Inf),
    tmax=c(TRUE,FALSE),
    aucinf.obs=c(FALSE, TRUE)
  )
my.data <- PKNCAdata(d_conc, intervals=intervals_manual)
my.data
pk.nca(my.data)
```

However, auclast is first parameter in PKNCA.options() and it defaults to c(TRUE,FALSE) in the above example.

```r
str(PKNCA.options("single.dose.aucs"))
```

The option for the tmax parameter is c(FALSE,TRUE), however two values are reported, one for time 24h and one for Infinity. So adding tmax=c(TRUE,FALSE) manually will instruct PKNCA to use max=c(TRUE,TRUE). I would expect that PKNCA only reports what I asked for i.e. tmax=c(TRUE,FALSE).

The only way I could obtain the desired result was to change tmax to c(TRUE,FALSE) in PKNCA.options("single.dose.aucs") which is less convenient (code not shown).

```r
intervals_manual <-
  data.frame(
    start=0,
    end=c(24, Inf),
    auclast=c(TRUE,FALSE),
    tmax=c(TRUE,FALSE),
    aucinf.obs=c(FALSE, TRUE)
  )
my.data <- PKNCAdata(d_conc, intervals=intervals_manual)
my.data
pk.nca(my.data)
```

**Comment by billdenney** [comment]
@RaySub, thanks for your interest in PKNCA.  I'm happy to help, though I'm not certain that I understand the questions correctly.  If I don't answer what you're asking, please let me know.

In general, PKNCA calculates whatever is required for the requested parameters.  For example, when calculating `aucinf.obs`, one input required is the `auclast`, so it is also calculated.  And, any calculated parameters are returned in the listing-style format (`as.data.frame()`).  This includes both the requested parameters and the other parameters needed for the requested ones.

For `PKNCA.options("single.dose.aucs")`, that is intended to be a generic option for setting the interval definitions for single-dose data.  In my experience, it is typically useful for small molecules (where once-daily dosing is the norm and time is measured in hours).  In general, I find that most users need to specify the intervals manually for actual study results.

For your specific question about `tmax`, it is required for calculating half-life which is required for calculating `aucinf.obs`.  That is why it shows up twice in the output data.frame.  It is requested in the first, 0-24, interval and it is needed in the second, 0-Inf, interval.  It does not show up in the summary table:

``` r
library(PKNCA)
#> 
#> Attaching package: 'PKNCA'
#> The following object is masked from 'package:stats':
#> 
#>     filter
source(url("https:///raw.githubusercontent.com//billdenney//pknca//main//tests//testthat//generate.data.R"))

d_conc <-
  PKNCAconc(
    generate.conc(nsub=1,
                  ntreat=1,
                  time.points=c(0, 1, 2, 4, 6, 8, 12, 24, 36, 48),
                  nstudies=1,
                  nanalytes=1,
                  resid=0),
    conc~time|treatment+ID)

intervals_manual <-
  data.frame(
    start=0,
    end=c(24, Inf),
    tmax=c(TRUE,FALSE),
    aucinf.obs=c(FALSE, TRUE)
  )
my_data <- PKNCAdata(d_conc, intervals=intervals_manual)
my_obj <- pk.nca(my_data)
#> No dose information provided, calculations requiring dose will return NA.
as.data.frame(my_obj)
#> # A tibble: 13 × 7
#>    treatment    ID start   end PPTESTCD            PPORRES exclude
#>    <chr>     <int> <dbl> <dbl> <chr>                 <dbl> <chr>  
#>  1 Trt 1         1     0    24 tmax                 4      <NA>   
#>  2 Trt 1         1     0   Inf tmax                 4      <NA>   
#>  3 Trt 1         1     0   Inf tlast               48      <NA>   
#>  4 Trt 1         1     0   Inf clast.obs            0.0955 <NA>   
#>  5 Trt 1         1     0   Inf lambda.z             0.0500 <NA>   
#>  6 Trt 1         1     0   Inf r.squared            1.00   <NA>   
#>  7 Trt 1         1     0   Inf adj.r.squared        1.00   <NA>   
#>  8 Trt 1         1     0   Inf lambda.z.time.first  6      <NA>   
#>  9 Trt 1         1     0   Inf lambda.z.n.points    6      <NA>   
#> 10 Trt 1         1     0   Inf clast.pred           0.0955 <NA>   
#> 11 Trt 1         1     0   Inf half.life           13.9    <NA>   
#> 12 Trt 1         1     0   Inf span.ratio           3.03   <NA>   
#> 13 Trt 1         1     0   Inf aucinf.obs          19.9    <NA>
summary(my_obj)
#>  start end treatment N              tmax aucinf.obs
#>      0  24     Trt 1 1 4.00 [4.00, 4.00]          .
#>      0 Inf     Trt 1 1                 .  19.9 [NC]
#> 
#> Caption: tmax: median and range; aucinf.obs: geometric mean and geometric coefficient of variation
```

<sup>Created on 2022-10-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by billdenney** [comment]
@RaySub , If you still have a question about this, feel free to reopen the issue.

**Comment by RaySub** [comment]
Hi Bill,

Your explanations sound perfectly clear to me.

Thanks,

Ray
