### ISSUE TITLE
max.aucinf.pext

### ISSUE THREAD

**Issue by ksl31** [billdenney/pknca#20]
For this argument in PKNCA.options(), by setting a value, will PKNCA automatically exclude any parameters with aucinf that are greater than this value? When I leave it as the default setting (20), I'm getting the parameters with max.aucinf.pext>20%.

**Comment by billdenney** [comment]
I've done a lot of work on the `exclude` functions, and with a commit I'm about t add, you can now apply the option setting to your results.  See `?exclude_nca` for instructions on how.

If you have any questions, please let me know!
