### ISSUE TITLE
Vz and Vd

### ISSUE THREAD

**Issue by ksl31** [billdenney/pknca#22]
Hi Bill,
I am having trouble getting PKNCA to calculate Vz. My code is as follows for interval specifications.

my.intervals <- data.frame(start=0,
                           end=inf,    
                           cmax=TRUE,
                           tmax=TRUE,
                           aucinf=TRUE,
                           auclast=TRUE,
                           aucall=TRUE,
                           aumcinf=TRUE,
                           aumclast=TRUE,
                           aumcall=TRUE,
                           cl=TRUE,
                           aucpext=TRUE,
                           vz=TRUE)

**Error in pk.nca.interval(conc = tmpconcdata[, col.conc], time = tmpconcdata[,  : 
  Cannot find argument 'auc' for NCA function 'pk.calc.mrt'**

In your manual, **pk.calc.vd(dose, aucinf, lambda.z)** and **pk.calc.vz(dose, auc, kel, unitconv)**. Is the formula in PKNCA for Vz=Dose/(AUC x Kel) whereas Vd=Dose/(AUCinf x lambda z)? It seems like this is different from what I know, where Vz=Dose/(AUCinf x lambda z). 

Thank you!

**Comment by billdenney** [comment]
I believe that I just fixed this, please let me know if you still have an issue.
