### ISSUE TITLE
option for improving performance by reducing bookkeeping

### ISSUE THREAD

**Issue by certara-msale** [billdenney/pknca#226]
Would like to add an option to remove any unnecessary "bookkeeping" to improve performance,
thanks
Mark Sale
mark.sale@certara.com

**Comment by billdenney** [comment]
@certara-msale, I did some profiling of the code, and I think that for large numbers of subjects (I was testing with 1000) there may be a ~50% improvement in speed with the PR that I just merged.  Can you please give it a shot and let me know if it helps?

**Comment by certara-msale** [comment]
Thanks Bill, will be next week I think, report due Monday


Mark Sale M.D.
Vice President
Integrated Drug Development
***@***.***
Remote-Forestville CA
Office Hours 9 AM - 5 PM Eastern Time
+1 302-516-1684
www.certara.com
[Certara Logo]

**Comment by billdenney** [comment]
Based on offline emails, we were able to speed it up about 30% with the improvements in the recent PR.
