### ISSUE TITLE
Column for parameters unit in output and unit conversion

### ISSUE THREAD

**Issue by ksl31** [billdenney/pknca#25]
It would be nice to have a column for units in the final output. Is it possible to include options to specify desired units for certain parameters?

**Comment by billdenney** [comment]
I do plan to add units to the package through a collaboration with someone who is writing a thorough units package.  The way it will come in is you will specify the units for the concentration, time, and dose in your input data.  The unit conversion package would then track the units that change with addition, subtraction, multiplication, division, logarithms, and exponentiation.

As a workaround until that package is completed:  If you want to specify units for certain parameters, I'd create a data.frame with the parameter name and the units then merge it with the results.

**Comment by billdenney** [comment]
I've added units.  To see how to use them, see this vignette: http://billdenney.github.io/pknca/articles/unit-conversion.html

I'd love to hear any thoughts that you have about their use.
