### ISSUE TITLE
Steady-State NCA parameters error

### ISSUE THREAD

**Issue by ksl31** [billdenney/pknca#26]
When calculating steady state parameters, cav and ctrough using the following interval, error messages appear.

 my.intervals <- data.frame(start=0,
                           end=Inf,
                           cmax=TRUE,
                           tmax=TRUE,
                           aucinf=TRUE,
                           auclast=TRUE,
                           aucall=TRUE,
                           aumcinf=TRUE,
                           aumclast=TRUE,
                           aumcall=TRUE,
                           cl=TRUE,
                           aucpext=TRUE,
                           vss=FALSE, ptr=TRUE, ctrough=TRUE)

**Error in pk.nca.interval(conc = tmpconcdata[, col.conc], time = tmpconcdata[,  : 
  Cannot find argument 'start' for NCA function 'pk.calc.cav'**

**Error in pk.nca.interval(conc = tmpconcdata[, col.conc], time = tmpconcdata[,  : 
  Cannot find argument 'start' for NCA function 'pk.calc.ctrough'**

**Comment by billdenney** [comment]
I'm just about to commit a fix for this.  Can you please confirm that it works for you when you update to the latest GitHub version of PKNCA?
