### ISSUE TITLE
sparse_se and sparse_df missing from get.interval.cols()

### ISSUE THREAD

**Issue by john-harrold** [billdenney/pknca#292]
I'm using the latest version of PKNCA off of GitHub. When I run the following:

```r
names(PKNCA::get.interval.cols())
```

I see `sparse_auclast` but I do not see `sparse_se` and `sparse_df`. I think they should be in there. If they were left off intentionally, can you add them :). I use the `get.interval.cols` function in order to determine the names of valid PKNCA parameters. Perhaps I should use something else?

**Comment by billdenney** [comment]
Yep, they should be there.  The linked PR should fix that.  I will merge assuming that all the tests succeed.
