### ISSUE TITLE
Native pipe and R version dependency

### ISSUE THREAD

**Issue by kylebaron** [billdenney/pknca#304]
Hi @billdenney - 

Now that the native pipe is in PKNCA code, do you need to start depending on a R 4.1 or greater? 

I think this was causing CI failure on R 4.0.5 for us (we're pulling in pmxTools for some tests and that brings PKNCA with).

Kyle

https://github.com/billdenney/pknca/blame/1888d3f621c91b8fd5a6fb41bc363f79bb5b974d/R/class-summary_PKNCAresults.R#L266

https://github.com/metrumresearchgroup/mrgsolve/pull/1206

**Comment by billdenney** [comment]
Thanks for pointing that out.  I will remove the native pipes so that I can decrease the version dependency.

**Comment by billdenney** [comment]
@kylebaron, since I recently created a new version, I don't want to get on CRAN's bad list by releasing too often.  Is this a significant issue or is it okay to wait ~1 month (which I believe is the CRAN-suggested interval between versions)?

**Comment by kylebaron** [comment]
@billdenney - thanks; we have a workaround for our immediate need. This is only coming in when all Suggested packages are requested and not affecting basic installation of mrgsolve. Whenever it makes sense to resubmit, I think it should be fine (for us). 

KTB
