### ISSUE TITLE
clean.conc.blq: feats for tmax reference and default keep

### ISSUE THREAD

**Issue by billdenney** [billdenney/pknca#343]
### Discussed in https://github.com/billdenney/pknca/discussions/340

<div type='discussions-op-text'>

<sup>Originally posted by **Gero1999** December  6, 2024</sup>
Hello, thank you for this great package! I would like to propose two potential features for this function:

- **Add before.tmax & after.tmax in `conc.blq` list argument.** In NCA is very typical to use `tmax` as a reference on how to deal with BLQ data. I think that it would be very easy to change PKNCA `clean.conc.blq` to include for the list definition "before.tmax"and "after.tmax" to make this possible, but please let me know what you think! 

- **Default keep values in `conc.blq` list argument .** I feel that when a user does not define a specific scenario in the list argument (i.e, middle) they simply don't want to perform any action. For that reason, I believe it would make sense to change `PKNCA.options` to put keep as default when an element list is missing.

Let me know what you think of these requests, I will also try to link a PR with a potential solution. Feel free to give it a look, change or ignore it! 

Pull request in #341 </div>

**Comment by billdenney** [comment]
Thanks for the proposal. I understand the desire for the changes. I think that the PR needs a few additional considerations:

1. I strongly hesitate to change any default behavior (breaking changes that alter behavior can cause issues with existing code). So, I would not want to have a default option where it is "keep"; the user can specify that, if desired. And, I would rather someone explicitly define a value rather than making an assumption of the preferred default.
2. Reading the code (but not running it), it seems like the behavior could be complex to understand if both the "first"/"middle"/"last" and "before.tmax"/"after.tmax". I would think that a user could want the following sets, but mixing "middle" and "before.tmax"/"after.tmax" seems like it would be undefined:
    1. "before.tmax"/"after.tmax" must both or neither be specified (you can't have "before.tmax" and not "after.tmax", or vice-versa)
    2. "before.tmax"/"after.tmax" is not allowed with "middle" (precedence would be unclear)
    3. "first" takes precedence over "before.tmax"; if both are given the concentrations before `tfirst` are handled by "first"; concentrations after `tfirst` but before `tmax` are handled by "before.tmax"
    4. "last" takes precedence over "after.tmax"; if both are given, then concentrations after `tlast` are handled by "last" and concentrations between `tmax` and `tlast` are handled by "after.tmax"
3. Please add tests to verify all scenarios are fully validated including any expected errors. PKNCA targets 100% test coverage. And, it's easier to verify that code works the way it's intended by reviewing successful tests.

(I'm commenting here because I tend to use issues for conceptual discussion of features in a PR and the PR for more code-focused discussion.)

**Comment by Gero1999** [comment]
Thanks for the feedback @billdenney, I understand and agree with your concerns. Considering them I would like to propose a counteroffer that might provide an easy solution:

1. Eliminate default "keep" feature for `conc.blq` so the user needs to specify always all arguments
2. Make checks so only one set of names is used in `conc.blq` list. Either the user can specify `first`, `middle`, `last` or `before.tmax`, `after.tmax`. That way we elude collapsing strategies. 

Let me know if you agree with this, I will push it on #341 so you can review the latest changes

**Comment by billdenney** [comment]
@Gero1999 , those changes make sense to me. Thanks! I'll do a code review in the PR.

**Comment by billdenney** [comment]
Completed in #341
