### ISSUE TITLE
Feature Request: Automatic Outlier Detection

### ISSUE THREAD

**Issue by DBartlettHP** [billdenney/pknca#347]
The derivation of a logical `OUTLIER` column based on the makeup of data across various intervals.

- Ensure that, depending on the data structure, the data is grouped accordingly for these derivations. 
  (Some data contains multiple endpoints to make the derivations on.) 

- Ensure that appropriate options exist for users to be able to **add their own conditions** for potential outliers.

- Perhaps there can be a "default" system for outlier checking, which can be overridden by various options for user adjustability.

```r
# Supposing the data contains multiple different testing values across different treatments:
# Example - Concentration of "7-OH-CBD" in patients receiving "5% CBD", 
#          and Concentration of "CBD-7-COOH" in patients receiving "10% CBD".

# Flagging of outliers values here being the values passed the timepoint of maximum concentration
# that are greater than their next timepoint concentration. (Potentially swapped values)
ret <-
data |>
group_by(SUBJID, TRTP, PCTEST) |>
mutate(
      MAX_CONC = max(PCSTRESN, na.rm = TRUE),
      MAX_TIME = PCTPTNUM[which.max(PCSTRESN)],
      OUTLIER = case_when(
        PCTPTNUM > MAX_TIME & PCSTRESN < lead(PCSTRESN) ~ TRUE,
        TRUE ~ FALSE
      )
    ) |>
    select(-MAX_CONC, -MAX_TIME)
```

**Comment by billdenney** [comment]
@DBartlettHP, this is a good idea, but it is beyond the scope of typical NCA calculations.

Going into the details of the ways to do NCA data validations will take a lot of challenges to make it work well. Eventually, I think it would be a good idea to have the following data validation reside within PKNCA, but I would prefer that the experimentation of how to get it right take place outside of PKNCA:

1. Detect outliers (unexpected BLQ, unexpected measurable concentrations, outliers that are measurable)
2. Detect missing PK samples (not just NA values but rows that are not present in the dataset, for example all participants in a group have a 4-hour nominal time measurement, but one is missing the 4-hour nominal time measurement)
3. Detect unexpected present PK samples (note unscheduled samples; if only one participant has a 4-hour nominal time measurement an no one else has one, note that)
4. Try to detect samples that were swapped

There are probably more to consider. But again, I think those should start in a different setting and then come to PKNCA when mature.
