### ISSUE TITLE
Make PKNCA_CRAM.pdf more informative

### ISSUE THREAD

**Issue by sibojan** [billdenney/pknca#35]
Hi Bill,

I found that a lot of functions in the PKNCA_CRAM manual do not include examples of their usages. For example, there is only a general usage for the function pk.calc.tmax.  To make the manual more informative,  you may want to add a real dataset example to show people how to use it.  In the meantime, to list all the functions in alphabetical order make the manual less readable.  It is appreciated if you can develop another textbook version.

Thank you,

Sibo

**Comment by billdenney** [comment]
Hi Sibo,

It looks like you found the examples that are run in the vignettes as you mentioned them in #36.  I would point you to the vignettes for the big picture of how to use PKNCA.  I will look into adding more examples in the manual and for ways to sort the manual better.

Thanks,

Bill

**Comment by billdenney** [comment]
I'm glad that you like it.  If you have data that you can share to make a good example, please let me know.  The more contributors we have, the better the package becomes!

**Comment by sibojan** [comment]
No problem. I can share some simulated data later on.

**Comment by sibojan** [comment]
Hi Bill,

I have some data, which may be useful for developing the tutorial.  How can I share it with you?  My email address is sibojan@ufl.edu.

Sibo
