### ISSUE TITLE
Error with PKNCAdose: "The formula must be one-sided"

### ISSUE THREAD

**Issue by abrahamans** [billdenney/pknca#39]
Hi Bill,
I am running into the following error while using 
> PKNCAdose

**Error in PKNCAdose(d.dose, Dose ~ Time | Subject) : 
  The formula must be one-sided**

I tried to recreate the theophylline example and get the same error message as above. 
```
library(PKNCA)
library(knitr)

##clear workspace
rm(list = ls())
my.conc <- PKNCAconc(as.data.frame(datasets::Theoph), conc ~ Time|Subject)
d.dose <- unique(datasets::Theoph[datasets::Theoph$Time == 0,
                                  c("Dose", "Time", "Subject")])
my.dose <- PKNCAdose(d.dose, Dose~Time|Subject)
```
Any help or reference to an existing solution would be helpful.

Thanks,
Anson

**Comment by billdenney** [comment]
I'm unable to replicate the issue in my environment.  I ran precisely the code you supplied above, and I got the only expected messages ("Assuming route of administration is extravascular" and "Assuming instant dosing (duration=0)").  Can you confirm that you're using the current version from CRAN (0.8.1)?

My complete sessionInfo is below for the system I tested it on:

```
sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] knitr_1.15  PKNCA_0.8.1

loaded via a namespace (and not attached):
[1] plyr_1.8.4      parallel_3.3.2  tools_3.3.2     Rcpp_0.12.8     nlme_3.1-131    grid_3.3.2      digest_0.6.12   lattice_0.20-34
```

**Comment by abrahamans** [comment]
I am running it on a cluster that has "ver 0.6", which I am unable to change. Was this an issue in 0.6?

**Comment by billdenney** [comment]
I believe that version didn't support including the dose amount.  Can you retry with the following:

```
my.dose <- PKNCAdose(d.dose, ~Time|Subject)
```

The current version is much-improved relative to version 0.6.  If possible, I'd recommend upgrading at your next scheduled cluster maintenance/upgrade window.

**Comment by abrahamans** [comment]
Your solution works. Thanks.
