### ISSUE TITLE
[Feature Request] checkpoint for numeric data - easy to fix

### ISSUE THREAD

**Issue by sibojan** [billdenney/pknca#40]
I found the PKNCAdata (conc,dose)  will accept the data, even the column type of concentration is character.  Then, it will run into error when NCA is performed. However, the error message below is not informative as respect to the root of the problem. 
It would be helpful to have a checkpoint for the data type before the NCA is run.  In this way, it ensure all the input data are numeric. 

 **> my.data <- PKNCAdata (conc,dose) %>% pk.nca (.)
Error in conc.2 + conc.1 : 
  Error with interval ID=1, start=0, end=24: non-numeric argument to binary operator**

**Comment by billdenney** [comment]
That is relatively straight-forward.  Just to make sure I understand the request correctly:  The idea is to give an error early and informatively if concentration, time, (and to extend) or any column that must be numeric isn't.  Right?

**Comment by billdenney** [comment]
Hi @sibojan,

I just committed a patch for this.  Thanks for letting me know about it and please let me know if you have other feature requests or questions on using PKNCA!

Thanks,

Bill
