### ISSUE TITLE
calculation of Vss for multiple-dose PK

### ISSUE THREAD

**Issue by dennisanoe** [billdenney/pknca#44]
Bill,

Can you confirm that the formulas used for calculating MRT and Vss for intravascular dosing accounts for differences between single-dose PK and multiple-dose PK?

single-dose PK:
   MRTsd = AUMCinf/AUCinf - infusion duration/2
   Vss = CLinf*MRTsd
multiple dose PK, including washout data after last dose (to calculate AUCinf after last dose):
   MRTmd = AUMCtau/AUCtau  + (TAU * (AUCinf - AUCTAU ) / AUCTAU - infusion duration/2
   Vss = CLtau*MRTmd

Thanks.

**Comment by billdenney** [comment]
The equations are for the extravascular MRT (mean residence time) including the MAT (mean absorption time) aligning with the SDTM definitions:

MRTinf = AUMCinf/AUCinf
MRTlast = AUMClast/AUClast

Similarly for Vss:

Vss = CL * MRT

**Comment by dennisanoe** [comment]
Bill,
The issue here is that the formulas for CL, Vz, MRT, and Vss are different in the steady state setting.
The most widely appreciated difference is that CL is not dose/AUCinf but dose/AUCtau. In PKNCA this would be Cl.last for the steady-state dosing interval.
Similarly, Vz is not (dose/AUCinf)/lambaz but (dose/AUCtau)/lambdaz. I'm not sure that PKNCA uses the right formula for Vz. I am worried that it calculates dose/AUCinf (even if that parameter is not requested) and uses that number in calculating Vz.
The formulas fro MRT and Vss are quite different, as noted earlier in this thread.

I think that it would be useful to add an argument to PKNCA for single dose/multiple dose, similar to the argument for extravasular/intravascular, which directs the program to the appropriate formula for the sampling setting. 

Thanks,
Dennis

**Comment by billdenney** [comment]
Hi Dennis,

That's reasonable.  I've reopened the issue to ensure that I add these.  They will not likely be aware of single vs. multiple dosing at the beginning, but adding mrt.md as a separate way of calculating MRT is straight-forward (almost-- the mechanics of sending tau through the calculations is not there yet).

Thanks,

Bill

**Comment by billdenney** [comment]
I'm about to push an update that enables a few new parameters that cover these situations:  mrt.md.obs, mrt.md.pred, vss.md.obs, vss.md.pred

**Comment by Juliliang** [comment]
Hi Dennis,

It is a valuable point for multiple dose PK parameter calculation. 
Could you please share the source of the formulas to derive MRT and Vss mentioned earlier in this thread? Thanks in advance for your time!

Thanks,
Juli

**Comment by dennisanoe** [comment]
Juli,
You can find the formula for multiple dose MRT in the documentation for
Certara WinNonlin and in the PHUSE White Paper on NCA (
http://www.phusewiki.org/wiki/index.php?title=File:PhUSE_CSS_WhitePaper_PK_final_25March2014.pdf).
Multiple dose Vss = multiple dose MRT*CLtau =  multiple dose
MRT*(dose/AUCtau).
Dennis


Resist

**Comment by kirstenbergmann** [comment]
Hi Bill

Related to the question on this issue. Regarding Vz. Is this calculated as described by Dennis, i.e. 
Vz is not (dose/AUCinf)/lambaz but (dose/AUCtau)/lambdaz

I can see that there is a fix for Vss at multiple dose but not for Vz. 

Best regards
Kirsten

**Comment by billdenney** [comment]
For future reference, the PhUSE whitepaper has moved to https://phuse.s3.eu-central-1.amazonaws.com/Deliverables/Standard+Analyses+and+Code+Sharing/Analyses+%26+Displays+Associated+to+Non+Compartmental+Pharmacokinetics+with+a+focus+on+Clinical+Trails+Version.pdf
