### ISSUE TITLE
calculation of Cav

### ISSUE THREAD

**Issue by dennisanoe** [billdenney/pknca#45]
The formula for Cav
Cav = auc.last / (end - start)
depends on the value of "end". 

"end" needs to be set t >= the largest value of t.last in the observed data in order for that time/concentration pair to be included in the calculation of auc.last. (Subject 1 in the PKNCA theophylline dataset is an example. His/her last time/concentration pair is (24.37, 3.28). "end" has to be set >= 24.37 in order for (24.37, 3.28) to be included in the calculation of auc.last for that subject). Setting "end" to be >= all observed t.last values means Cav will be underestimated for all subjects except those for whom observed t.last = "end".

If it is desired to calculate Cav based on observed data, the formula should be
Cav = auc.last / (t.last - start)
for auc.last and t.last as found in the parameter interval.

If it is desired to calculate Cav based on a stipulated length of the dosing interval, the formula could be
Cav = auc.tau / (tau - start)
where auc.tau is an interpolated/extrapolated auc value and tau is set by the analyst. 

Thanks,
Dennis

**Comment by wsloand** [comment]
Hi Dennis,

Thanks for this comment.  I think that you're right: the most commonly anticipated method would use the AUCINT (note interval not infinite).  I have on my roadmap to add the AUCINT as another type of AUC calculation (where AUCINT is calculated by imputing times after tlast if tlast < end).

I'll ensure that's in the next version and that Cav uses that AUC as the default.

Would this cover your needs?

Thanks,

Bill

**Comment by dennisanoe** [comment]
Thanks for the quick response, Bill. 

The calculation of AUCINT (start, end) solves the problem if:
the analyst wishes to estimate Cav for an ideal dosing interval (start, end),
extrapolation is used if observed tlast < end, interpolation is used if observed tlast > end, and
Cav = AUCINT / (end - start)

However, if the analyst wants to estimate Cav for the observed dosing interval (start, observed tlast), the solution needs to be: 
Cav = auc.last / (tlast - start)
where auc.last corresponds to the observed dosing interval (as currently implemented in PKNCA) 

Currently PKNCA uses a hybrid of the approaches: auc.last, observed dosing interval, for the numerator and end-start, ideal dosing interval, for the denominator.

If you wish to provide flexibility for the analyst you may want to let him/her select either auc.last and Cav.last OR auc.end and Cav.end. Of course, having this choice would have downstream consequences on the calculation of multiple-dose CL, MRT, Vz, and Vz.

If it is going to take a while to get around to implementing interpolation/extrapolation for calculation of AUCINT, I recommend the simple expedient of changing the formula for Cav to:
Cav = auc.last / (tlast - start)
which is a consistent definition of Cav as regards observed versus ideal dosing intervals.

Thanks for your patience,
Dennis

**Comment by dennisanoe** [comment]
Bill,
I recognize that my terminology in the preceding note is erroneous in cases in which tlast < time of collection of end-of-dosing-interval specimen (teod).

The correct statements are:

If the analyst wishes to estimate Cav for an ideal dosing interval (start, end),
extrapolation is used if observed tlast < end, interpolation is used if observed tlast > end
Cav = AUCINT / (end - start)

If the analyst wants to estimate Cav using the observed dosing interval data (start, teod), 
Cav = auc.last / (teod - start)
whether tlast = teod or tlast < teod

Thanks,
Dennis

**Comment by billdenney** [comment]
Thanks Dennis!

Overall, I think that `Cav = AUCINT/(end - start)` is the most consistent result, but when extrapolating, it requires a reasonable estimate of half-life.

Both methods, `Cav = auc.last/(end - start)` or `Cav = auc.last/(teod - start)`, introduce bias when there are BLQ samples.  `end - start` is biased low and `teod - start` is biased high.  And, the degree of bias is half-life dependent (one compartment example below).  (The bias is balanced when MRT = tlast/2.)  I'm a torn on which is the best method.  Do you know a reference where this may have been discussed more/settled?

(In the code below, you can play with the `current.half.life` value.)

```r
library(dplyr)
library(caTools)
library(ggplot2)

current.half.life <- 2

d.sim <- mutate(data.frame(time=0:24),
                conc=2^(-time/current.half.life))
d.sim$Cav.teod <-
  sapply(d.sim$time,
         FUN=function(teod, data) {
           with(data[data$time <= teod,],
                trapz(x=time, y=conc)/teod)
         },
         data=d.sim)
d.sim$Cav.end <-
  sapply(d.sim$time,
         FUN=function(teod, data) {
           with(data[data$time <= teod,],
                trapz(x=time, y=conc)/max(data$time))
         },
         data=d.sim)

ggplot(d.sim[!is.na(d.sim$Cav.teod),],
       aes(x=time)) +
  geom_line(aes(y=Cav.teod, colour="teod")) +
  geom_line(aes(y=Cav.end, colour="end")) +
  labs(x="Tlast",
       y="Cav")
```
![image](https://user-images.githubusercontent.com/10359931/27151063-605f7222-5117-11e7-972f-ed8bd29820c3.png)
![image](https://user-images.githubusercontent.com/10359931/27151079-6d99edf0-5117-11e7-974d-ad9757d00fad.png)

**Comment by billdenney** [comment]
Hi @dennisanoe,

FYI, the most recent updates to PKNCA over the last couple of weeks implement AUCint in a few flavors.  I'm still fine-tuning the parameter naming and in some cases precisely how they work, but I wanted to let you know that this is nearing completion now.

Thanks,

Bill
