### ISSUE TITLE
How to work with data with concentration and time but not dose?

### ISSUE THREAD

**Issue by tofu84** [billdenney/pknca#47]
Hi all,

I want to conduct a regular NCA analysis to generate AUC and Cmax. However, for part of my dataset from a few subjects, there was no dose information, but only concentrations and times (up 24 hrs after the dose). Can the package PKNCA be used to work on the data I have?

Thanks!

**Comment by billdenney** [comment]
PKNCA can work with your data.

When dosing is not provided, you must provide the `intervals` argument to PKNCAdata similar to the following:

```r
my_conc <- PKNCAconc(my_conc_data, conc~time|subject)
my_intervals <- data.frame(start=c(0, 168), end=c(24, 192), auclast=TRUE, cmax=TRUE)
my_data <- PKNCAdata(my_conc, intervals=my_intervals)
my_results <- pk.nca(my_data)
```

**Comment by tofu84** [comment]
Thank you very much, Bill! It works!

Nan
