### ISSUE TITLE
Individualised intervals for NCA

### ISSUE THREAD

**Issue by htjollyn** [billdenney/pknca#50]
Dear Bill

Some subjects in my dataset have (after iv bolus at t=0) a first observation at 0.08 h, some have it at 0.15 h.
 
If I want to use an automated approach, I would need to adjust the intervals for AUC calculation per individual, as the package does not allow me to put c(0, Inf) as integration interval.

Can you please advise me how I can resolve this issue?
 
Thanks a lot!
Huybrecht

**Comment by billdenney** [comment]
There are two methods that can likely solve your issue:
* Individualized intervals
* Impute a concentration at time=0, and all intervals are 0-inf
    * Concentration could either be 0 or calculate C0 and impute that.

To generate individualized intervals, you could use code like below (I’m typing this directly into GitHub so there could be bugs):
```r
library(dplyr)
# In the summarize call, add all the parameters you want to calculate
my_intervals <- 
  my_data %>%
  group_by(Subject_ID) %>%
  summarize(start=min(time), end=max(time), cmax=TRUE, aucinf.obs=TRUE, tmax=TRUE, half.life=TRUE) %>%
  ungroup()
# Then use my_intervals in the call to PKNCAdata like:
my_data <- PKNCAdata(my_conc, my_dose, intervals=my_intervals)
```

To impute concentration at time=0:

```r
library(dplyr)
my_imputed <-
  my_data %>%
  group_by(Subject_ID) %>%
  summarize(time=0, concentration=0)
my_updated_data <- bind_rows(my_data, my_imputed)
my_updated_data <- my_updated_data %>%
  arrange(Subject_ID, time)
my_conc <- PKNCAconc(my_updated_data, concentration~time|Subject_ID)
```

**Comment by billdenney** [comment]
@pharmdwoman, The answer is notably different than the individualized intervals question, so I am moving it to a separate issue.  I will link that issue back here and mention you in it so that you can find it.
