### ISSUE TITLE
Error when using paste() for variable names in PKNCAdose formula

### ISSUE THREAD

**Issue by htjollyn** [billdenney/pknca#51]
Dear Bill

I tried to implement (as part of larger script) for automation the following code with below stated error message. Can you have a look at this and give me feedback on how to solve this one?
Thank you!

d_conc <- df[...]
d_dose <- df[...]

idv = c("TIME")
dv = c("CONC")
dose = c("DOSE")
groupvars = c("ID")                

# Put your concentration data into a PKNCAconc object
my_conc <- PKNCAconc(d_conc, 
                     paste(dv, "~", idv, "|", groupvars))

# Put your dose data into a PKNCAdose object
## must have the same names between concentration and dose objects.)
my_dose <- PKNCAdose(d_dose,
                     paste(dose, "~", idv, "|", groupvars),
                     route = "intravascular", duration = 0)  # for iv bolus

> my_conc runs appropriately
> my_dose gives following error: Error in findOperator(form, "~", "left") : Cannot handle class character

**Comment by billdenney** [comment]
The `formula` argument to PKNCAconc and PKNCAdose are expecting a formula.  If you wrap your `paste` in `as.formula`, it should work:

```r
my_dose <- PKNCAdose(d_dose,
    as.formula(paste(dose, "~", idv, "|", groupvars)),
    route = "intravascular", duration = 0) # for iv bolus
```
