### ISSUE TITLE
Add time=0, and concentration=0 to data set

### ISSUE THREAD

**Issue by cokkies** [billdenney/pknca#52]
Hi billdenney.

Is there any smart way to add a additional data in form of (time=0 & concentration=0) to data set, where some subjects lack data points corresponding time=0 & concentration=0? As you did mention  that PKNCA also does not impute time zero so it looks like I would also need to do that before running PKNCA. 

Best regards

**Comment by billdenney** [comment]
Hi,

This is standard data management in R (nothing specific to PKNCA).  Also, I typed this directly into GitHub, so there could be bugs/typos.

```r
library(dplyr)
my_data <- # Load your data from somewhere like a .csv file
# Assuming that the time column is called "time" and the subject column is called "subject"
# and the only grouping is the column "treatment"
subject_zero <-
  my_data %>%
  group_by(treatment, subject) %>% # Add all your grouping columns here
  summarize(has_time_0=any(time %in% 0)) %>%
  filter(!has_time_0) %>% # Only keep subjects without time 0
  select(-has_time_0) %>% # drop that column
  mutate(time=0, concentration=0)

my_data_updated <- bind_rows(my_data, subject_zero)
```

**Comment by Sibojang9** [comment]
Is there any way to build this into the PCKNCA function by adding an argument?

**Comment by billdenney** [comment]
@Sibojang9, There is not currently a function to automatically do this.  This request is effectively part of #21.
