### ISSUE TITLE
my.data <- PKNCAdata(my.conc, my.dose) error

### ISSUE THREAD

**Issue by quantny** [billdenney/pknca#53]
I keep getting a error that will not let me run this function.

Error:
> my.data <- PKNCAdata(my.conc, my.dose)
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic
In addition: Warning messages:
1: In is.na(time.dosing) :
  is.na() applied to non-(list or vector) of type 'NULL'
2: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
3: In is.na(object) :
  is.na() applied to non-(list or vector) of type 'NULL'

This works fine for another analysis that same drug different day datasets setup in exactly the same way. Saved and read into R as .csv files

Thanks for any help you can provide.

Regards

Justus

**Comment by billdenney** [comment]
At a glance, it looks like there is something wrong with the dose time column.  Can you please confirm that the dose time column exists in your dosing dataset?

If it does, can you please provide a full reproductive example?

**Comment by quantny** [comment]
Yes of course here is my dose dataset. 

Regards

Justus

**Comment by billdenney** [comment]
I'm guessing that you just attached this to an email, but it didn't appear on GitHub.  Can you please attach the concentration-time dataset, dosing dataset, and the code you were trying (all code from data load to the error).

**Comment by quantny** [comment]
library(XML)
library(reshape)
library(psych)
library(PKNCA)
library(tidyr)
library(dplyr)
library(magrittr)

dose.times
substrRight <- function(x, n){
  substr(x, nchar(x)-n+1, nchar(x))
}

setwd("~/Documents/RRD/Eiger/LNF_RTN/LOWR2/Briefing Package/Analysis/PK/NCA")
#input <-read.table("day28.txt", sep="\t", header=TRUE)
input <- read.csv("day28.csv",header=T)

cols <- c(1,2,5,6,7,8)
input[,cols] <- apply(input[,cols], 2, function(x) as.character(x))
input$DOSE <- as.integer(input$DOSE )
input <- as.data.frame(input)
dd <- subset(input, input$TIME == 672)
dd%<>%select(ID, TIME, DOSE)
input%<>%select(ID, TIME, CONC)

dose.times <- seq(0, 672, by=12)
data <- dd
ids<-unique(data$ID)
output<-NULL

for(i in 1:length(ids))
{
  
  data2<-data.frame(subset(data,ID==ids[i],select=c(ID,TIME,DOSE)))
  time<- dose.times
  dose<-data2$DOSE
  ID <-unique(data2$ID)
  tmp2 <- data.frame("ID"=rep(ID,length(i)),
                     "TIME"=time,
                     "DOSE"=rep(dose,length(i)))
                     
  output <- rbind(output,tmp2)
}


output$ID <- as.character(output$ID )

PKNCA.options(auc.method="lin up/log down", min.hl.points=3)

my.conc <- PKNCAconc(input, CONC~TIME|ID)

my.dose <- PKNCAdose(output, DOSE~TIME|ID, duration = 0)

my.data <- PKNCAdata(my.conc, my.dose)

[day28.xlsx](https://github.com/billdenney/pknca/files/1423712/day28.xlsx)

**Comment by quantny** [comment]
Bill

I found the error because of the main I created my dose record there was 2 subjects without a first time point of 672. So the dose file had 2 less subjects than the concentration file. Thanks for all your help. 

Regards,

Justus

**Comment by billdenney** [comment]
Hi Justus,

I'm glad that you were able to find the issue.  I'm going to keep this open so that I make the error message you received more informative.

Also, separately from PKNCA, I'm creating a package of PK datasets for general use (https://github.com/billdenney/PKdata).  Can I include the dataset from this issue in that?  If so, can you please share more info on the study (mostly what drug was used, maybe what NCTID is it)?  Do you have day 1 and day 28 data that you could share?

**Comment by quantny** [comment]
Bill,

I will ask my client, though I don't think the data is fully useful for what you want the sample window from 0 to tau is too short for a drug with zero order clearance not seen in this window.

**Comment by billdenney** [comment]
I just committed a fix.  Please let me know if you have any future issues!
