### ISSUE TITLE
Dose independent NCA on MC Ct simulation results

### ISSUE THREAD

**Issue by bfreed3** [billdenney/pknca#54]
## The Problem

I was looking to a basic, dose-less NCA on a large amount of MC simulated Ct data, grouped by compound (n=2 cpds), tissues, (n=6 tissues), and simulated individuals (n=1000). I simulated a 100 step Ct profile for each of these. Therefore, doing the math, you can tell I had a huge data file (65 MB .csv, ~1.2 million lines, 5 columns). I wanted to run NCA on it, just to generate a Cmax, Tmax, AUClast, T1/2 (using last 30 simulated time points), and AUCinf.pred for each individual and tissue, by compound.
 
I tried to do this in Phoenix 8 WNL, and it crashed repeatedly. Certara support looked into it, and they had no problems running it on their side. They said it was probably my iMac-VM-win7 setup that was at fault. However, I also tried running it on a stand alone win7 machine meeting all the software/hardware criteria, and it still crashed. I still can't rule out that is isn't something about the win set up at our institution or in our lab that's at play here though.

## The Solution (courtesy of Bill Denney):

```{r, echo=TRUE}
library(PKNCA)
library(tidyr)
library(dplyr)

predCtproc <- read.csv("predCtproc.csv")

predCtproc <- rename(predCtproc,compound=Compound,subject=Indiv..,matrix=Matrix,
                     time=Pred.Time,conc_ngmL=DV_ngmL,conc=DV)

pkconc <- PKNCAconc(conc~time|compound+matrix+subject,data=predCtproc)

pkintervals <- data.frame(
  start=0,
  end=48,
  cmax=TRUE,
  tmax=TRUE,
  auclast=TRUE,
  aucinf.pred=TRUE,
  half.life=TRUE
)

pkdata <- PKNCAdata(pkconc,intervals=pkintervals)

start.time <- Sys.time()
pkresults <- pk.nca(pkdata)
end.time <- Sys.time()
run.time <- end.time-start.time
run.time 

prms <- c("auclast","cmax","tmax","half.life","aucinf.pred")
median.na <- function(x) {median(x, na.rm=TRUE)}
quantprob.na <- function(x) {quantile(x, probs=c(0.05, 0.95), na.rm=TRUE)}

PKNCA.set.summary.vector <-
  function(vector, point, spread, rounding=list(signif=3), reset=FALSE) {
    invisible(lapply(vector, FUN=PKNCA.set.summary, point=point, spread=spread, 
           rounding=rounding))
  }

PKNCA.set.summary.vector(prms, median.na, quantprob.na)

pksummary <- summary(pkresults)
write.csv(pksummary,"pksummary.csv",row.names=FALSE)

pkresout <- as.data.frame(pkresults)
write.csv(pkresout,"pkresout.csv",row.names=FALSE)

wilcox <- as.data.frame(pkresults) %>%
  group_by(matrix,PPTESTCD) %>%
  filter(!is.na(PPORRES)) %>%
  summarize(Wilcox=wilcox.test(PPORRES[compound=="MEPB"],
                               PPORRES[compound=="TA"],paired=FALSE)$p.value)

wilcoxhl <- as.data.frame(pkresults) %>%
  filter(!is.na(PPORRES)) %>%
  filter(PPTESTCD=="half.life"&matrix=="Plasma") %>%
  summarize(Wilcox=wilcox.test(PPORRES[compound=="MEPB"],
                               PPORRES[compound=="TA"],paired=FALSE)$p.value)
```

**Comment by billdenney** [comment]
Thank you for summarizing our email conversation!

I'll keep this open to ensure that I do the following:
* Improve the PKNCA.set.summary function so that multiple endpoints can be provided simultaneously.
* Provide additional documentation on the PKNCA.set.summary function and generally ways to summarize data following analysis with PKNCA (possibly via a new vignette).

**Comment by billdenney** [comment]
I just fixed the two issues listed above with the most recent commit.
