### ISSUE TITLE
Warning message related "exclude"?

### ISSUE THREAD

**Issue by RyosukeOno** [billdenney/pknca#55]
I used your code and data of Theophylline in your web  (https://cran.r-project.org/web/packages/PKNCA/vignettes/Example-theophylline.html), which was a little modified to avoid error message for “exclude”, the following error message is shown after “pk.nca(my.data.automatic)” and these parameters were not calculated.  The exclude was set according to the instruction. 

--- PKNCAconc in th instruction ---
exclude (optional) 
The name of a column with concentrations to exclude from calculations and summarization. If given, the column should have values of NA or "" for concentrations to include and non-empty text for concentrations to exclude.

--- Warning message ---
> my.results.automatic <- pk.nca(my.data.automatic)
There were 24 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In FUN(X[[i]], ...) :
  Error with interval Subject=11, start=0, end=24: No data for interval
2: In FUN(X[[i]], ...) :
  Error with interval Subject=11, start=0, end=Inf: No data for interval

--- Code ---
library(PKNCA)

## It is always a good idea to look at the data
knitr::kable(head(datasets::Theoph))

## By default it is groupedData; convert it to a data frame for use
d.conc <- as.data.frame(datasets::Theoph)
d.conc$exclude <- ""
my.conc <- PKNCAconc(d.conc, conc~Time|Subject, exclude="exclude")

## that first.
d.dose <- unique(datasets::Theoph[datasets::Theoph$Time == 0,
                                  c("Dose", "Time", "Subject")])
d.dose$exclude <- ""
knitr::kable(d.dose,
             caption="Example dosing data extracted from theophylline data set")

my.dose <- PKNCAdose(d.dose, Dose~Time|Subject, exclude="exclude")

my.data.automatic <- PKNCAdata(my.conc, my.dose)
knitr::kable(PKNCA.options("single.dose.aucs"))

knitr::kable(my.data.automatic$intervals)

my.intervals <- data.frame(start=0,
                           end=Inf,
                           cmax=TRUE,
                           tmax=TRUE,
                           aucinf.pred=TRUE,
                           auclast=TRUE)
my.data.manual <- PKNCAdata(my.conc, my.dose,
                            intervals=my.intervals)
knitr::kable(my.data.manual$intervals)

my.results.automatic <- pk.nca(my.data.automatic)

**Comment by billdenney** [comment]
Thanks for pointing out that the code isn't the same as the documentation!  Rather than making it a warning if an empty string is given, I'm going to update the code so that blanks are converted to NA internally.
