### ISSUE TITLE
Extraction of  the $single.dose.aucs from the pk.nca results

### ISSUE THREAD

**Issue by sibojan** [billdenney/pknca#56]
I want to get a summary of those options for my run. I found that it is in the result$data but not clear on how to extract them. 

```
$single.dose.aucs
  start end auclast aucall aumclast aumcall auclast.dn aucall.dn aumclast.dn  
1     0  24    TRUE  FALSE    FALSE   FALSE      FALSE     FALSE       FALSE       
2     0 Inf   FALSE  FALSE    FALSE   FALSE      FALSE     FALSE       FALSE   
```

Thank you,

Sibo

**Comment by billdenney** [comment]
Hi Sibo,

I'm not sure that I understand your question.  To get the results of each individual from your analysis, you should use `as.data.frame(result)`.  To get summary results from your analysis, you should use `summary(result)`.

If that doesn't answer your question, can you please provide an example in code and what you're wanting to extract?

Thanks,

Bill

**Comment by sibojan** [comment]
Hi Bill,

Thank you for your prompt reply.  I figured it out. **my_results$data$options$single.dose.aucs** will lead me to the option I want to see,  where I get a idea of what was  and what was NOT computed. 

`my_results <- PKNCAdata (conc,dose) %>% pk.nca (.)`
`my_results$data$options$single.dose.aucs`

Thank you,

Sibo

**Comment by billdenney** [comment]
That is the way to get the info on what **could have been** calculated for the current data based on default options.  What **was** calculated is in `my_results$data$intervals`.

"single.dose.aucs" is the default interval selection for single-dose data.  If you want to specify different choices for your current analysis, the best way to do that is via the `intervals` options to `PKNCAdata`.

**Comment by sibojan** [comment]
Thank you for the tips, which are very helpful.
