### ISSUE TITLE
Output Summary

### ISSUE THREAD

**Issue by NeilBhattacharya** [billdenney/pknca#57]
What would be the command to obtain the output of individual NCA parameters by subject. I used the summary(my.results) but it gives me limited information. How do we find out what was the summary statistics used e.g. median vs. mean etc. Again thanks for your help

**Comment by billdenney** [comment]
To get all the results, run `as.data.frame(my.results)`.

It's a good point that the summary statistics aren't easy to determine.  The defaults are that parameters typically assumed to be log-normally distributed (AUCs, Cmax, etc) are summarized by geometric mean and geometric %CV; discrete parameters (e.g. Tmax) are summarized by median and range; and half-life is summarized by arithmetic mean and standard deviation.  (Technically, you can get the function itself from `summary_funs <- PKNCA.set.summary()`, but that gives you the function body not the function name.)

**Comment by billdenney** [comment]
@NeilBhattacharya, I just pushed a change mentioned in #58 so that you now get a summary of what was used for summarizing each parameter.

**Comment by NeilBhattacharya** [comment]
Thanks Bill.

Neil
