### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NeilBhattacharya** [billdenney/pknca#59]
In the routine step I get the following error. A look at the dataset does not provide any obvious clues. 
my.data <- PKNCAdata(my.conc, my.dose)
Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : 
  'x' must be atomic
In addition: Warning messages:
1: In is.na(time.dosing) :
  is.na() applied to non-(list or vector) of type 'NULL'
2: In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
3: In is.na(object) :
  is.na() applied to non-(list or vector) of type 'NULL'

**Comment by billdenney** [comment]
Can you please share all the code and data you used to get to this point?

**Comment by NeilBhattacharya** [comment]
I think I got the cause of the error. It was possibly due to missing time 0 for some subjects. Therefore when d.dose was used to select time at 0, the doses might have gone missing.

**Comment by billdenney** [comment]
Ah then, that looks like the same issue as #53.
