### ISSUE TITLE
pk.nca(my.data) Error in x[[1]] : subscript out of bounds

### ISSUE THREAD

**Issue by lucidca** [billdenney/pknca#60]
I got stuck at the last step of the PKNCA :

"> my.results <- pk.nca(my.data)
Error in x[[1]] : subscript out of bounds"

There were no other error messages when the conc, dosing and intervals were merged using PKNCAdata().  

Any suggestions? Thanks.

**Comment by lucidca** [comment]
This turned out to be due to the mismatched dosing and conc records. Some subjects had PK without dosing info, while one subject had dosing but no observable PK. The issue is now resolved. Thanks.

**Comment by billdenney** [comment]
I'm glad that you were able to trouble-shoot it so quickly.  This is the same issue as #53, and I intend to fix it (by giving a clearer error and working around missing data when feasible) in the next release.
