### ISSUE TITLE
What dose "default dosing information" exactly mean?

### ISSUE THREAD

**Issue by sibojan** [billdenney/pknca#61]
Hi Bill,

Sometime, I only need calculation of AUC and terminal slope without providing any dosing information.
` PKNCAdata (conc)`  output  **No dose information provided, assuming default dosing information.**
Dose that mean dose zero?
Thank you,

Sibo

**Comment by billdenney** [comment]
Hi Sibo,

Good point that it's unclear.  The "default dosing information" is null info (no dosing time, no dosing amount).  For internal consistency within PKNCA, an empty dosing object is created which in effect tells PKNCA, "no dose information was provided".

I will update the warning to remove the "assuming default dosing information" part.

Thanks,

Bill

**Comment by sibojan** [comment]
Thank you so much for the clarification. Maybe more hints can be provided to the end users, e.g. “No dose information provided. Only xxx parameters are computed" , which is mostly helpful to people new to NCA analysis.
