### ISSUE TITLE
Can you import dosing from NONMEM

### ISSUE THREAD

**Issue by mattfidler** [billdenney/pknca#62]
It seems your dosing/events are a bit different from NONMEM's dosing/events.  Is there some compatability layer I'm missing?

**Comment by billdenney** [comment]
Currently, there is no direct import from NONMEM.  It is part of the longer-term plans to build a mrgsolve-NONMEM-importer (discussion of this is in https://github.com/metrumresearchgroup/mrgsolve/issues/303), and when developed, it will live in the [PKNCA.portation](/billdenney/pknca.portation) library.

**Comment by billdenney** [comment]
To clarify a bit more, the initial intent of the PKNCA package is to analyze data from clinical studies where raw data are collected as dose start/end time (for infusion doses).

You can also use the `realize_addl` function in the [/metrumresearchgroup/mrgsolve](mrgsolve) library to  get closer to the required PKNCA input.

**Comment by mattfidler** [comment]
Thanks for the clarification.

**Comment by billdenney** [comment]
(That's not to say that it can't be used for simulations-- PKNCA has been used to analyze >50k simulated doses in a single run as described in #54 and done elsewhere.)

**Comment by mattfidler** [comment]
Thanks.  I was thinking of using it with simulations, though I do not personally use mrgsolve.  (Although I think Kyle and Devin are excellent developers and the software is also excellent).
