### ISSUE TITLE
`lambda.z.time.first` reports the observation number not the time

### ISSUE THREAD

**Issue by CJGodfrey** [billdenney/pknca#63]
In the output the variable `lambda.z.time.first` contains the sequential observation number (e.g. 8th observation) instead of the time of that observation.  The latter seems the more relevant result to report.

**Comment by billdenney** [comment]
Just to confirm, not an issue?

**Comment by CJGodfrey** [comment]
RIght.  I realized it was my mistake...just coincidence that the 8 hour observation was the 8th observation.
