### ISSUE TITLE
psuedo-point insertion required for time 0, conc 0 data point

### ISSUE THREAD

**Issue by slyrus** [billdenney/pknca#65]
My original question was: "I would have assumed that at time 0, conc would be zero and if, say, I had data at 1,2,4,8, and 24 hours, I would treat 0,0 as the first time point. I can't do this unless I had a dummy time point. Is that the best way to handle this issue?"

And @billdenney replied:

"The requirement for a pseudo-point insertion is an intentional limitation of the way that the intervals are calculated now.  I don’t want PKNCA to assume things that may be wrong.  For instance, some people enter time as time after most recent dose, and in a multi-dose study time=0 on Day > 1 isn’t necessarily 0.  The next version of PKNCA introduces several variants of AUCINT which will impute accounting for prior data and dose.  The AUCINT variants will give you your imputed 0,0 point."

This is also addressed by https://github.com/billdenney/pknca/issues/21 but I've added this issue in the hopes that others facing similar issues may see the advised workaround.

**Comment by billdenney** [comment]
In the next version of PKNCA (0.9.0 or the version currently on GitHub), you can use the `aucint` family of parameters to enable imputation of any point (including 0,0).

For now, yes, manual imputation is required for the CRAN version (0.8.4 or earlier).

**Comment by slyrus** [comment]
Ok, thanks. The more I think about it, the more I'm getting comfortable with the status quo, but I look forward to seeing the aucint stuff.
