### ISSUE TITLE
How to get summary information back from a summary of PKNCA data?

### ISSUE THREAD

**Issue by slyrus** [billdenney/pknca#67]
If I want to extract things like auclast and aucinf from a PKNCAresults object, what's the best way to do so?
If I extract the data from the aucinf.obs column I get a string of the form "103 [10.3]". Surely there's a better way than parsing that string.

**Comment by billdenney** [comment]
Run `as.data.frame` on the results , and you’ll recieve all the individual calculations.

**Comment by slyrus** [comment]
I'm not sure I follow. If I do: pk.nca.results <- pk.nca(my.data) do I call as.data.frame on pk.nca.results? pk.nca.results$result? summary(pk.nca.results)? None seem to give the answer I'm looking for. I can get the data for individual animals, but I can't get the summary without resorting to something like this:
```
calc.pk.statistics <- function (results, route, dose, start=0, end=24) {
    result <- results$result

    aucinf.obs <- PKNCA::geomean(result[result$PPTESTCD == "aucinf.obs" &
                                       result$Route == route &
                                       result$Dose == dose &
                                       result$start == start &
                                       result$end==end,c("PPORRES")])

    aucinf.pred <- PKNCA::geomean(result[result$PPTESTCD == "aucinf.pred" &
                                       result$Route == route &
                                       result$Dose == dose &
                                       result$start == start &
                                       result$end==end,c("PPORRES")])

    auclast <- PKNCA::geomean(result[result$PPTESTCD == "auclast" &
                                       result$Route == route &
                                       result$Dose == dose &
                                       result$start == start &
                                       result$end==end,c("PPORRES")])

    half.life <- PKNCA::business.mean(result[result$PPTESTCD == "half.life" &
                                            result$Route == route &
                                            result$Dose == dose &
                                            result$start == start &
                                            result$end==end,c("PPORRES")])
    data.frame(route = route,
               dose = dose,
               start = start,
               end = end,
               auclast = auclast,
               half.life = half.life,
               aucinf.obs = aucinf.obs,
               aucinf.pred = aucinf.pred)
}
```
I'm would imagine there's a better way.

**Comment by billdenney** [comment]
I misunderstood the original question and thought that you were looking for the individual results not the numeric values of the summary results.

There’s not currently a way to receive the values of the summary results as numbers, but I can add that as a feature for the next creation.

**Comment by slyrus** [comment]
Ok, thanks. What I showed above seems to be an acceptable workaround for the moment. Is that basically equivalent to how you compute those values? Thanks!

**Comment by billdenney** [comment]
Your method is generally similar.  The actual method used (https://github.com/billdenney/pknca/blob/1e98eb6ea3a4d9e0facefcc7495c2c18629e5469/R/class-PKNCAresults.R#L132-L230) generalizes the selection of groups and excludes values based on the `exclude` column (and finding the name of the exclude column is also generalized).

**Comment by slyrus** [comment]
Did a method to extract the summary results (as numbers) ever make it in? Thanks!

**Comment by billdenney** [comment]
It's not there yet mainly because I can't think of a good way to make it work.  The issue is that the point and spread estimates for parameters differ in number of values produced.  For example, the default point and spread estimates for Cmax are geometric mean and geometric CV (two values), while for Tmax, it's median and range (three values).

To generalize that becomes pretty cumbersome with each column becoming a list column (which I always find painful to work with).  Then there would be the issue that sometimes no value is requested or no value is calculable which would mean the point estimate and variability would need to be managed differently for them with some form of indicator that meshes well with numeric-only values (or again a cumbersome list column).

If you have specific ideas on how to implement it, I'm interested to have another perspective.

**Comment by slyrus** [comment]
Hmm... Interesting point. I have tried to generalize some of the grouping code and that has been helpful for avoiding long lists of duplicated code, but don't (yet) address the issue you raise. To give you an idea of what I mean, take a look at the following:

```
pknca.group.median.values <- function(results,  ...) {
    group_var  <- dplyr::quos(...)
    tidyr::spread(results$result %>%
                  dplyr::group_by(!!! group_var, PPTESTCD) %>%
                  tidyr::drop_na(PPTESTCD) %>%
                  dplyr::summarise(median=stats::median(PPORRES)) %>%
                  tidyr::drop_na(PPTESTCD) %>%
                  dplyr::ungroup(),
                  key="PPTESTCD",
                  value="median")
}

pknca.group.median.values(pk.nca.results, Dose, Treatment) %>%
    filter(Treatment == "CPD-1234" & Dose == 100) %>%
    select(auclast)
```

But I note that this doesn't play nicely with PKNCA::business.median for some reason that I haven't yet figured out. Perhaps this approach could be extended to handling multiple values (speaking of which, all of this always makes me miss common lisp and its handling of things like multiple-values, destructuring-bind, macros, etc... but I digress...)

**Comment by palar359** [comment]
Hi,
I have few questions:

1) How can I get Vd's and CL's in "my.results" output (I see all other parameters except these two) in my set of data? 
2) How can I pull individual Cmax and AUCs by subjects corresponding to their subject IDs?

Thanks
Arindam

**Comment by billdenney** [comment]
@palar359, I moved the questions to a new issue since they aren't related to the question of how to get the method used for summarization.

**Comment by billdenney** [comment]
I've added some documentation on a method to extract numeric summaries, but I don't see a great way to make this simpler.
