### ISSUE TITLE
How to carry along additional variables?

### ISSUE THREAD

**Issue by JoannaPeng** [billdenney/pknca#70]
Is it possible to carry along additional variables for PKNCAconc() and superposition()? For example, carry along the nominal times, so that the superposition is done using the actual times, but the summary plot (median and confidence interval) is generated using nominal times. Thanks!

**Comment by billdenney** [comment]
Unfortunately, it’s not possible to carry through variables that change with time.  For outputs from `PKNCAconc`, many of the outputs combine many time points (for example, it would be unclear what row to use for half-life).

Superposition has a similar problem where many rows in the input become part of the output.  For example, if your input times were 0, 2, 4, 8, 12, 24, and 48 hours and your superposition interval were 24 hours, then the 0, 24, and 48 hour inputs directly go into the 0 hour output.  If you want times that look like nominal times in your output, you can use the `additional.times` argument to superposition.

If you have time-invariant values that you want in the output, you can merge them back in from your source data.

**Comment by JoannaPeng** [comment]
Thank you, Bill. Your input was very helpful. I was able to use additional.times to specify the time points of interest and get rid of all other time points so that i could do the summary stats.
