### ISSUE TITLE
Enable Unit-handling for concentration, time, and dose

### ISSUE THREAD

**Issue by billdenney** [billdenney/pknca#73]
The `units` package now has the ability to manage custom units, store mixed sets of units in a single vector, and other useful tools for managing units.

Enable unit handling in PKNCA.  Challenges will include:

1. handling dose units separately from concentration units.  (the dose-normalized Cmax may have units of e.g. "(ng/mL)/'mg dosed'" and not "1/L" as would be fully simplified.)
2. Calculated parameters will need to have units re-assigned.  (E.g. half-life will need the same units as its input.)
3. Mixed units may be provided (e.g. time could be in hours, days, and weeks in the same dataset).

(This is related to #25)

**Comment by slyrus** [comment]
+1. It would be very nice if in addition to the PPORRES data in the result we had PPORRESU.

**Comment by billdenney** [comment]
I've added units. To see how to use them, see this vignette: http://billdenney.github.io/pknca/articles/unit-conversion.html

I'd love to hear any thoughts that you have about their use.
