### ISSUE TITLE
Improve Single-Subject Handling

### ISSUE THREAD

**Issue by billdenney** [billdenney/pknca#74]
Data when the subject is not specified (i.e. single subject data) does not work with most PKNCA functions.  That should be fixed.

**Comment by john-harrold** [comment]
So my assumption here is that if I have a data frame with a single subject I cannot specify a formula without a grouping (conc~time or conc~time|) don't seem two work. Right now is it necessary to have a dummy grouping column in both the concentration and dose data frames?

**Comment by billdenney** [comment]
@john-harrold 
That's right.  Currently, PKNCA requires some form of grouping.  The simplest is to add a dummy grouping column.
