### ISSUE TITLE
package loading

### ISSUE THREAD

**Issue by jeslo328** [billdenney/pknca#77]
Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

If you think that you have found a bug or you have a feature request, please briefly describe your problem and what output you expect.

If you have a question, please ask what you're curious about ideally with expected input, output, and what you have tried (a reprex, if feasible).

---

Brief description of the problem
I am trying to load this PKNCA pacakge in another PC and I am not able to and keep getting the below error message.
I can install the PKNCA  [ install.packages("PKNCA") ]
But when library(PKNCA) 

Error: package or namespace load failed for ‘PKNCA’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘Rcpp’

please advice

```r
# insert reprex here
```

**Comment by billdenney** [comment]
PKNCA shouldn't directly require Rcpp, but not having it available is what appears to be the error.

Can you please let me know what platform you're running on (Windows, Mac, or Linux)?  What version of R are you using (the output of `sessionInfo()` is most helpful)?

**Comment by jeslo328** [comment]
Hi

I am running on Windows and R version 3.5.1

**Comment by billdenney** [comment]
Did you see any errors while installing PKNCA?  As I'm installing PKNCA on Linux, it appears to automatically install Rcpp.

Can you remove and reinstall the package, and paste everything that shows up after you type `install.packages("PKNCA")`?

**Comment by jeslo328** [comment]
I could see the library folder in the win-library. but as soon as i load the library it give error

**Comment by billdenney** [comment]
My guess is that there was an error during the installation that caused Rcpp not to install.  Can you try removing the PKNCA folder in `win-library` and reinstall it?

**Comment by jeslo328** [comment]
Hi Bill

I retried after removing and reinstalling. You are right - the problem
might be due to incomplete package download.
I noticed the package load was slow in my PC.
At the end this problem was no more.

On a separate note,
since I am just trying out this package can you advice / dataset / hands on
that can be used for me to explore and understand better particularly the
manual way.

Really appreciate it and thank you

**Comment by billdenney** [comment]
I'd recommend starting with the vignettes (https://cran.r-project.org/web/packages/PKNCA/index.html) the ones to start with are:
* https://cran.r-project.org/web/packages/PKNCA/vignettes/Introduction-and-Usage.html
* https://cran.r-project.org/web/packages/PKNCA/vignettes/AUC-Calculation-with-PKNCA.html
* https://cran.r-project.org/web/packages/PKNCA/vignettes/Selection-of-Calculation-Intervals.html
