### ISSUE TITLE
Improve Errors, Messages, and Warnings with Layered Capturing and Modification

### ISSUE THREAD

**Issue by billdenney** [billdenney/pknca#80]
Errors, warnings, and messages (raised conditions) are currently handled in the most nested function (e.g. `pk.calc.half.life()`).  The messages associated with those raised conditions do not give the context of condition such as the subject number or interval start and end.

It would be beneficial to update condition handling so that the context is present in the message.  Message capturing like that described in https://github.com/tidyverse/purrr/issues/426#issuecomment-414902143 could be the basis of this handler.

**Comment by slyrus** [comment]
I'm not sure if this is related or not, but I'm having a hard time figuring out what's wrong with my code (presumably) when I get an error in pk.nca:

```
 > pk.nca.results <- PKNCA::pk.nca(my.data)
Error in parallel::mclapply(X = splitdata[mask_has_interval], FUN = pk.nca.intervals,  : 
  (converted from warning) all scheduled cores encountered errors in user code
```

Any suggestions on how to extract the error from the mclapply stuff?

**Comment by billdenney** [comment]
I've never seen that one before, and it looks odd.

I have a love-hate relationship with error reporting via mclapply: https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17122

Have you recently upgraded R?  Can you run other `mclapply` code without errors?  What operating system are you using (Linux, Windows, Mac, other)?

Also, it looks like you have `options(warn=2)` set.  Could you set `options(warn=1)` to get a better feel for where the issue is coming from?

There are a lot of warnings that can come from PKNCA (like half-life calculation warnings).  `options(warn=2)` will kill many PKNCA runs.

**Comment by slyrus** [comment]
I have recently-is updated R and this is on MacOS, but I think in general things are working fine. I can (successfully) call pk.nca with other data, and even with this set of data I can call pk.nca if I don't ask for aucinf (either pred or obs) but just ask for auclast. The data are admittedly a bit odd, it's from 5 time points at the end of a multi-day study. Perhaps there is too much noise in the data for the code to compute some values, which would be fine if I knew where things were failing and what assumptions I'm invalidating. (Or it could be something else entirely.)

**Comment by slyrus** [comment]
BTW, I'm using the latest PKNCA from GitHub.

**Comment by billdenney** [comment]
My best guess is an issue with warnings being converted to errors.  Can you give the output of `options("warn")`?  If the value is 2, that is almost definitely the problem, please set `options(warn=1)`.

If that doesn't fix it, can you share a reproducible example to help with troubleshooting?  PKNCA shouldn't give an error for any data at the time of calculation, and if it does, that's probably a bug.  (Regardless, the completely uninformative error you're getting appears to be a bug unless it's related to `options(warn=2)`.)

(If the data are confidential, perhaps you could remove any identifying information and multiply the concentration values by a random constant so that it would perform the same way to PKNCA without sharing the actual data?)

**Comment by slyrus** [comment]
Sorry for the long delay in replying. Warn is 0 (I think) and I still get the same error. If I try to make a standalone example I get a proper warning. Not sure how the warning is getting promoted to an error. So it sounds like there are two problems. This warning -> error thing and then the actual warning, that I can get from my standalone example:

```
Warning message:
In pk.calc.auxc(conc = conc, time = time, ..., options = options,  :
  Requesting an AUC range starting (0) before the first measurement (0.5) is not allowed
```
How can I compute AUC if I don't have 0 time points for all animals? I have 0 for some, and 0.5 for others. Should this be a separate "issue"? Thanks!

**Comment by billdenney** [comment]
This has been completed in prior PRs.
