### ISSUE TITLE
PKNCA returns AUC24h as AUClast irrespective of the time of the last observation.  How to obtain a true AUClast for single dose data

### ISSUE THREAD

**Issue by mgonza1** [billdenney/pknca#83]
Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

If you think that you have found a bug or you have a feature request, please briefly describe your problem and what output you expect.

If you have a question, please ask what you're curious about ideally with expected input, output, and what you have tried (a reprex, if feasible).

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by billdenney** [comment]
Can you please share an example of what you're specifically having trouble with (https://www.tidyverse.org/help/#reprex)?

As a guess, given the title, you may have set `end=24` for your interval.  See https://cran.r-project.org/web/packages/PKNCA/vignettes/Selection-of-Calculation-Intervals.html .

**Comment by mgonza1** [comment]
Hi Bill,

I was attempting to run the NCA using a simple example.  Attached is the code I used for concentration data set after a single dose. I assumed that AUClast parameter was by default set to the last measurable concentration. Upon checking my data I realized that AUClast parameter was actually reporting AUC24. Based on your vignette I see that I should add another line of code to specify the intervals. Is this correct?
[example.docx](https://github.com/billdenney/pknca/files/2397903/example.docx)

**Comment by billdenney** [comment]
Without the Excel data file, I can’t be sure, but there should be a row in the summary with `end=Inf` with the answer that you were expecting.

**Comment by mgonza1** [comment]
Hi Bill,

I've attached an example excel file and the script.  By default, it appears that PKNCA has AUClast set to end=24.  In cases where sampling is longer than 24hr would need to correct the default.  I attempted a few examples you provided but seem to be missing something as the result has not changed.

[Copy of dat4.xlsx](https://github.com/billdenney/pknca/files/2417404/Copy.of.dat4.xlsx)
[example.docx](https://github.com/billdenney/pknca/files/2417405/example.docx)

**Comment by mgonza1** [comment]
Hi Bill,

In one of the iterations I did have intervals= intervals1 but didn’t think that worked or I may have typed in another error in the process.  Thanks for clarifying, it works now.

However, cmax disappeared from the parameter list ( see indiv3) when I included the intervals for auc.last and aucinf.obs.  However, I was able to get it back by including it in the intervals.

intervals4<-data.frame(start=0, end=Inf, cmax=TRUE, auclast=TRUE, aucinf.obs=TRUE)

thank you,
Martha

**Comment by mgonza1** [comment]
Thank you Bill.

I am a bit confused as I didn’t request it in the initial run (prior to defining the intervals) and it was reported.  By default, PKNCA provided 14 parameters.  Once I specified the auc intervals, it provided 13 parameters.  I’ll read up a bit more and see if I can better understand this.

Thanks again!
Martha

**Comment by billdenney** [comment]
The way that the interval is automatically determined for you is described here:  https://cran.r-project.org/web/packages/PKNCA/vignettes/Introduction-and-Usage.html#automatic-interval-determination

I am acutely aware that documentation can always be improved, so if you think that this could be better described or linked within the documentation, please let me know.
