### ISSUE TITLE
Clarification of Values within Result Summary

### ISSUE THREAD

**Issue by JSC67** [billdenney/pknca#85]
Hi Dr. Denney,

I've just listened to your YouTube PKNCA tutorial (https://www.youtube.com/watch?v=WCmFrheYtcc), and at 20:31 at the bottom you have some summary() results.  Some of the quantities are in brackets, e.g. auclast is 74.6  [24.3], and tmax is 1.14 [0.630, 3.55]. I'm sorry to ask what's probably an obvious question (at least if you know the answer), but can you please elaborate on how to read this? What do the quantities inside and outside the square brackets mean, and why for some are the bracketed quantities a vector?

Also, is there a function for making pretty tabular output (e.g., HTML) similar to what WinNonlin can do?

Thanks for PKNCA!

-James

**Comment by billdenney** [comment]
Thanks for asking here!

The summarization is described in https://cran.r-project.org/web/packages/PKNCA/vignettes/Introduction-and-Usage.html#summarization-options-the-pknca.set.summary-function and using the `PKNCA.set.summary()` function.

The default for most parameters is that the value before the [] is the geometric mean and the value within the brackets is the geometric %CV.  Discrete values (like `tmax`) are summarized with median and range in brackets.

For making pretty tabular output, PKNCA doesn't do it directly, but there are loads of other packages that will convert a data.frame into html.  A good comparison of packages that will help convert data.frames into a variety of output formats is at https://hughjonesd.github.io/huxtable/design-principles.html (this isn't an endorsement of `huxtable` specifically, but the comparison table is the best I know of).  I use `pander` for most of my table generation and most of my reporting occurs via knitr/rmarkdown.

**Comment by billdenney** [comment]
FYI, I'm keeping this issue open as a note to improve the documentation around the summary results.

**Comment by billdenney** [comment]
Hi @JSC67,

I updated the summary of PKNCAresults so that:
* When printing the results to the screen, it will provide a caption indicating what the point estimate and spread are for each parameter.
* An attribute named `"caption"` is added to the summary output to provide that caption in a way that can be simply integrated into other reporting.  (Note that if you pass the PKNCAresults object to `pander::pander()`, the caption will be automatically added.)

**Comment by billdenney** [comment]
Good catch!  RStudio appears to add a newline even though I didn't put it in the code.

I'm working to add it, but I don't see the right way to make a test for the carriage return at the end (https://stackoverflow.com/questions/52932220/is-it-possible-to-use-testthatexpect-output-to-expect-a-carriage-return).  When I can make the test, it'll be fixed.
