### ISSUE TITLE
Function pk.calc.c0

### ISSUE THREAD

**Issue by wolfsem** [billdenney/pknca#86]
Dear Colleagues,

I would appreciate some insight and help to function pk.calc.c0. 

Which is not clear to me is whether or not I have to apply the function pk.calc.c0 prior calling pk.nca(my.dose, my.conc,my.intervals) or can this be implicitly included in the function pk.nca when specifying route='intravascular', duration=0 in function PKNCAdose?

In case that pk.calc.c0 functionalities are applied within function pk.nca, how can the method be specified (e.g. method “logslope” if first2 values are decreasing and method "c1" if not)?

Best regards & thank you for your time 

Martin

**Comment by billdenney** [comment]
Hi Martin,

At this time, you must call `pk.calc.c0()` and manually impute the C0 concentration within your dataset.  In the future, `pk.nca()` will implicitly include C0 calculation when `route="intravascular"` and `duration=0`.

Thanks,

Bill

**Comment by billdenney** [comment]
You can now calculate AUC for intravenous routes with the auciv* parameters (such as `aucivlast` for auclast with an IV bolus dose).   
 It does not automatically detect that you want it for the route and duration specification.  If you have additional questions, please let me know.
