### ISSUE TITLE
Placeholder issue

### ISSUE THREAD

**Issue by slyrus** [billdenney/pknca#87]
Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

If you think that you have found a bug or you have a feature request, please briefly describe your problem and what output you expect.

If you have a question, please ask what you're curious about ideally with expected input, output, and what you have tried (a reprex, if feasible).

---
Placeholder for examples of using additional.times.
```r
# to provide later
```

**Comment by billdenney** [comment]
It's not clear if you have a question here.  If not, no worries.  If so, can you please clarify what you're looking for?

**Comment by slyrus** [comment]
Sorry! Still gathering my thoughts. I was hoping to delete the issue but apparently I can't. Will reuse this issue when I gather my thoughts further. Sorry for the noise.
