### ISSUE TITLE
Order of grouping factors

### ISSUE THREAD

**Issue by sibojan** [billdenney/pknca#89]
HI Bill,

In my dataset, I have another column **population** as a grouping factor as follows:

Conc |**Population**
  1     |       adults
  3     |       adults
  1     |     children
  4     |    children

`PKNCAconc( d.conc,conc~Time| Population+Subject)  `gives the expected results for the average AUC for adults. However, `PKNCAconc( d.conc,conc~Time|  Subject+Population)  `dose not work.

It seems that  the order of **Population+Subject** matters. Since I cannot find a documentation for this,  Could you please shed some light?

Thank you,

Sibo
Univ of Florida

**Comment by billdenney** [comment]
Hi Sibo,

PKNCA assumes that the last grouping value is the subject.  This is documented in the `subject` argument to `PKNCAconc()`.  I will augment the documentation to clarify that detail in the `formula` argument to `PKNCAconc()`.  You can also explicitly provide which grouping variable is the subject using the `subject` argument.

In most cases, the NCA calculations are identical, but the summary uses the subject argument for grouping the summary statistics.
