### ISSUE TITLE
Formatting urine concentration and volume data

### ISSUE THREAD

**Issue by spradhan01** [billdenney/pknca#94]
I am trying to estimate renal clearance and amount excreted in urine. I am having difficulty figuring out how to format urine data. I have plasma concentration data along with urine concentration and urine volume data. Any instruction or example would help. 

Thanks,
Sudeep

**Comment by billdenney** [comment]
Hi Sudeep,

Thanks for your interest in PKNCA.  A limitation of PKNCA is that it doesn't currently calculate secondary parameters (like renal clearance), but you can calculate primary renal parameters (like Ae).  You would provide the urine concentration in the same column as the plasma concentration, and then you would give the volume in a column that you give as the `volume` argument to the `PKNCAconc()` function call.

For example:

```r
my_data <- data.frame(conc=1:3, vol=1:3, time=1:3, subject=1)
my_conc <- PKNCAconc(my_data, conc~time|subject, volume="vol")
# Ask for amount excreted
my_intervals <- data.frame(start=1, end=3, ae=TRUE)
# Put it into a data object
my_data <- PKNCAdata(my_conc, intervals=my_intervals)
# Calculate results and summarize them
my_res <- pk.nca(my_data)
summary(my_res)
```

**Comment by spradhan01** [comment]
Thank you very much Bill.
