### ISSUE TITLE
harmonic mean for half-life?

### ISSUE THREAD

**Issue by slyrus** [billdenney/pknca#96]
It's great that I can use median, geomean, etc... with pknca parameters. But this leads me to 1) should I be using the harmonic mean for t1/2? and 2) if so, should PKNCA have a harmmean function analogous to the geomean function?

**Comment by billdenney** [comment]
For the first question, I agree that the harmonic mean is a more theoretically-sound choice for central tendency.  But for the second question, I’m hoping to move functions that aren’t core to PKNCA out of the package (see #71).
