### ISSUE TITLE
Units for Vss and Cl calculations?

### ISSUE THREAD

**Issue by slyrus** [billdenney/pknca#97]
I'm unclear on what the units for Clearance an Vss are. I would have expected ml/hr/kg and l/kg but end up with values that are roughly 1e6 and 1e3, respectively, off. Can you clarify what the units are here? thanks!

**Comment by billdenney** [comment]
PKNCA (unfortunately) doesn't handle units yet (see #73).  So, the units are based on the input units without simplification.  If your input units for concentration are ng/mL, time are hours, and dose are mg, then:

* Clearance would be the units of dose/auc: mg/(hr*ng/mL)
* Vss would be units of clearance*MRT: mg/(hr*ng/mL)*hr = mg/(ng/mL)
