### ISSUE TITLE
pk.nca fails on R 3.6 install

### ISSUE THREAD

**Issue by slyrus** [billdenney/pknca#98]
I don't have a clean example of this yet but when I try to install a package that calls pk.nca (and assign the results to a variable), I get the following error:

** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
ERROR: hard-coded installation path: please report to the package maintainer and use ‘--no-staged-install’

**Comment by billdenney** [comment]
Earlier today, I upgraded to 3.6.0, and I didn't have any issues with PKNCA.  What package is it?  My guess is that the issue is with the other package because as far as I can think of, PKNCA doesn't use any path information.

**Comment by billdenney** [comment]
If you can find a way to make this error reproducible, please provide that and reopen the issue (or open a new issue).
