### ISSUE TITLE
Compute AUClast from sampled data?

### ISSUE THREAD

**Issue by slyrus** [billdenney/pknca#99]
Is it possible to use data from multiple animals where not all time points are measured to compute an "average" AUC? E.g., if i have data from time t=0,1,4,24 from some animals and from 0.5, 2, and 8 in other animals and I want to find some sort of average AUC. Can I do this with PKNCA?
thanks!

**Comment by billdenney** [comment]
This is a sparse PK study, so the request duplicates #1.  (So, the more direct answer is not yet, but I'm not likely to get there soon.  Pull requests are welcome!)  I don't know of sparse methods that support partially-repeated samples within subject.  As far as I'm aware, they assume that each sample comes from a separate animal.
